#-*-coding: utf-8-*-f
def address(city,area):
    address_keywords_dict = {
     'bj': {u"石景山": "/shijingshan/", u"北京": "/bj/", u"大兴": "/daxing/", u"北京周边": "/beijingzhoubian/", u"顺义": "/shunyi/",
	u"朝阳": "/chaoyang/", u"海淀": "/haidian/", u"燕郊": "/bjyanjiao/", u"平谷": "/pinggu/", u"宣武": "/xuanwu/", u"房山": "/fangshan/",
	u"崇文": "/chongwen/", u"西城": "/xicheng/", u"通州": "/tongzhouqu/", u"昌平": "/changping/", u"怀柔": "/huairou/", u"丰台": "/fengtai/",
	u"东城": "/dongcheng/", u"延庆": "/yanqing/", u"门头沟": "/mentougou/", u"密云": "/miyun/"},
'tj': {u"蓟县": "/jianxiantj/", u"红桥": "/hongqiaotj/", u"武清": "/wuqing/", u"东丽": "/donglitj/", u"河西": "/hexi/",
	u"天津周边": "/tianjin/", u"河东": "/hedong/", u"开发区": "/tjkaifaqu/", u"南开": "/nankai/", u"河北": "/hebeiqu/",
	u"西青": "/xiqingtj/", u"宝坻": "/baodi/", u"北辰": "/beichentj/", u"宁河": "/ninghexian/", u"和平": "/heping/",
	u"塘沽": "/tanggu/", u"大港": "/dagang/", u"汉沽": "/hangu/", u"津南": "/jinnantj/", u"静海": "/jinghaiqu/", u"天津": "/tj/"},
'sh': {u"静安": "/jingan/", u"南汇": "/nanhui/", u"上海": "/sh/", u"嘉定": "/jiading/", u"宝山": "/baoshan/", u"金山": "/jinshan/",
	u"闵行": "/minxing/", u"黄浦": "/huangpu/", u"虹口": "/hongkou/", u"松江": "/songjiang/", u"浦东": "/pudongxinqu/",
	u"奉贤": "/fengxiansh/", u"普陀": "/putuo/", u"青浦": "/qingpu/", u"徐汇": "/xuhui/", u"崇明": "/chongming/", u"卢湾": "/luwan/",
	u"上海周边": "/shanghaizhoubian/", u"杨浦": "/yangpu/", u"闸北": "/zhabei/", u"长宁": "/changning/"},
'cq': {u"长寿": "/changshou/", u"渝北": "/yubei/", u"两江新区": "/liangjiangxinqu/", u"璧山": "/bishanxian/", u"合川": "/hechuan/",
	u"江北": "/jiangbei/", u"万州": "/wanzhou/", u"石柱": "/cqshizhu/", u"永川": "/yongchuan/", u"重庆周边": "/chongqing/",
	u"北碚": "/beibei/", u"巴南": "/banan/", u"九龙坡": "/jiulongpo/", u"涪陵": "/fuling/", u"渝中": "/yuzhong/", u"重庆": "/cq",
	u"大渡口": "/dadukou/", u"沙坪坝": "/shapingba/", u"南岸": "/nanan/"},
    'other': {u"南充": "nanchong", u"漳州": "zhangzhou", u"沛县": "xzpeixian", u"清远": "qingyuan", u"黄南": "huangnan", u"莆田": "pt", u"佛山": "fs", u"海宁": "haining", u"武威": "wuwei", u"石河子": "shz",
              u"海安": "haian", u"鹰潭": "yingtan", u"三亚": "sanya", u"海口": "haikou", u"兴化": "xinghuashi", u"德州": "dz", u"清徐": "qingxu", u"鸡西": "jixi", u"宜宾": "yb", u"安阳": "ay", u"岳阳": "yy",
              u"呼和浩特": "hu", u"黑河": "heihe", u"榆林": "yl", u"茂名": "mm", u"阿拉尔": "ale", u"厦门": "xm", u"宿州": "suzhou", u"阿坝": "ab", u"南宁": "nn", u"东台": "dongtai", u"海北": "haibei",
              u"揭阳": "jy", u"伊春": "yich", u"三门峡": "smx", u"柳州": "liuzhou", u"东莞": "dg", u"长兴": "changxing", u"三明": "sm", u"周口": "zk", u"博罗": "boluo", u"靖江": "jingjiang", u"德宏": "dh",
              u"吕梁": "lvliang", u"上饶": "sr", u"安康": "ankang", u"海南": "hainan", u"玉溪": "yx", u"乐清": "yueqingcity", u"武汉": "wh", u"池州": "chizhou", u"襄阳": "xf", u"开封": "kaifeng",
              u"内江": "scnj", u"余姚": "yuyao", u"临沂": "linyi", u"淮南": "hn", u"朝阳": "cy", u"大庆": "dq", u"定西": "dx", u"禹州": "yuzhou", u"临沧": "lincang", u"吐鲁番": "tlf", u"金昌": "jinchang",
              u"兰州": "lz", u"遵义": "zunyi", u"泰安": "ta", u"南通": "nt", u"淮北": "huaibei", u"阜新": "fx", u"馆陶": "gt", u"松原": "songyuan", u"景德镇": "jdz", u"贵阳": "gy", u"贵港": "gg", u"常州": "cz",
              u"晋江": "jinjiangshi", u"五指山": "wzs", u"荆州": "jingzhou", u"新沂": "xinyishi", u"扬州": "yz", u"恩施": "es", u"林芝": "linzhi", u"四平": "sp", u"攀枝花": "panzhihua", u"台湾": "tw",
              u"澳门": "am", u"赣州": "ganzhou", u"威海": "weihai", u"荆门": "jingmen", u"淮安": "ha", u"玉林": "yulin", u"衡阳": "hy", u"桂林": "gl", u"义乌": "yiwu", u"红河": "honghe", u"杭州": "hz",
              u"临汾": "linfen", u"青岛": "qd", u"包头": "bt", u"广元": "guangyuan", u"平顶山": "pds", u"溧阳": "liyang", u"仙桃": "xiantao", u"台州": "tz", u"甘孜": "ganzi", u"如东": "rudong", u"甘南": "gn",
              u"龙岩": "ly", u"庆阳": "qingyang", u"诸城": "zc", u"中山": "zs", u"三沙": "sansha", u"新余": "xinyu", u"牡丹江": "mdj", u"霍邱": "hq", u"钓鱼岛": "diaoyudao", u"湖州": "huzhou",
              u"图木舒克": "tmsk", u"湘潭": "xiangtan", u"扬中": "yangzhong", u"漯河": "luohe", u"乐山": "ls", u"邳州": "pizhou", u"乌鲁木齐": "xj", u"如皋": "rugao", u"乌海": "wuhai", u"桐乡": "tongxiang",
              u"香港": "hk", u"通辽": "tongliao", u"焦作": "jiaozuo", u"十堰": "shiyan", u"石嘴山": "szs", u"宿迁": "suqian", u"合肥": "hf", u"黄冈": "hg", u"孝感": "xiaogan", u"果洛": "guoluo",
              u"南安": "nananshi", u"成都": "cd", u"海西": "hx", u"温州": "wz", u"延安": "yanan", u"晋城": "jincheng", u"邵阳": "shaoyang", u"鹤壁": "hb", u"瓦房店": "wfd", u"博尔塔拉": "betl",
              u"承德": "chengde", u"日照": "rizhao", u"晋中": "jz", u"怀化": "hh", u"潮州": "chaozhou", u"永新": "yxx", u"昌吉": "changji", u"常德": "changde", u"许昌": "xc", u"宜都": "yidou", u"烟台": "yt",
              u"福州": "fz", u"抚顺": "fushun", u"桐城": "tongcheng", u"济南": "jn", u"诸暨": "zhuji", u"广安": "ga", u"山南": "sn", u"楚雄": "cx", u"潜江": "qianjiang", u"石家庄": "sjz", u"张家界": "zjj",
              u"吉安": "ja", u"肇庆": "zq", u"信阳": "xy", u"海拉尔": "hlr", u"垦利": "kl", u"嘉善": "jiashanx", u"太原": "ty", u"辽源": "liaoyuan", u"临夏": "linxia", u"齐齐哈尔": "qqhr", u"双鸭山": "sys",
              u"苏州": "su", u"新乡": "xx", u"永州": "yongzhou", u"衢州": "quzhou", u"汕头": "st", u"聊城": "lc", u"温岭": "wenling", u"和田": "ht", u"日喀则": "rkz", u"娄底": "ld", u"黔西南": "qxn",
              u"洛阳": "luoyang", u"赵县": "zx", u"台山": "taishan", u"防城港": "fcg", u"天长": "tianchang", u"泰兴": "taixing", u"咸宁": "xianning", u"盘锦": "pj", u"葫芦岛": "hld", u"钦州": "qinzhou",
              u"镇江": "zj", u"江门": "jm", u"五家渠": "wjq", u"商洛": "sl", u"辽阳": "liaoyang", u"衡水": "hs", u"文山": "ws", u"梧州": "wuzhou", u"固原": "guyuan", u"郴州": "chenzhou", u"瑞安": "ruiancity",
              u"伊犁": "yili", u"黔南": "qn", u"本溪": "benxi", u"锦州": "jinzhou", u"随州": "suizhou", u"其他": "cn", u"大兴安岭": "dxal", u"商丘": "sq", u"绍兴": "sx", u"六盘水": "lps", u"济宁": "jining",
              u"湘西": "xiangxi", u"绥化": "suihua", u"吴忠": "wuzhong", u"金华": "jh", u"无锡": "wx", u"雅安": "ya", u"亳州": "bozhou", u"大丰": "dafeng", u"鄢陵": "yanling", u"邢台": "xt", u"廊坊": "lf",
              u"昆明": "km", u"深圳": "sz", u"宁波": "nb", u"巴彦淖尔市": "bycem", u"邯郸": "hd", u"黔东南": "qdn", u"运城": "yuncheng", u"黄石": "hshi", u"惠东": "huidong", u"琼海": "qh", u"保山": "bs",
              u"通化": "th", u"潍坊": "wf", u"贺州": "hezhou", u"沭阳": "shuyang", u"普洱": "pe", u"白城": "bc", u"资阳": "zy", u"阳春": "yangchun", u"曲靖": "qj", u"长治": "changzhi",
              u"湛江": "zhanjiang", u"哈尔滨": "hrb", u"呼伦贝尔": "hlbe", u"渭南": "wn", u"鞍山": "as", u"和县": "hexian", u"长沙": "cs", u"中卫": "zw", u"泸州": "luzhou", u"安庆": "anqing", u"陇南": "ln",
              u"菏泽": "heze", u"德阳": "deyang", u"铜仁": "tr", u"丹阳": "danyang", u"广州": "gz", u"德清": "deqing", u"阜阳": "fy", u"凉山": "liangshan", u"大连": "dl", u"丹东": "dandong", u"连云港": "lyg",
              u"萍乡": "px", u"六安": "la", u"定州": "dingzhou", u"梅州": "mz", u"嘉峪关": "jyg", u"沈阳": "sy", u"绵阳": "mianyang", u"海东": "haidong", u"遂宁": "suining", u"泉州": "qz", u"河源": "heyuan",
              u"营口": "yk", u"保定": "bd", u"那曲": "nq", u"宜昌": "yc", u"七台河": "qth", u"滁州": "chuzhou", u"朔州": "shuozhou", u"张家口": "zjk", u"铜陵": "tongling", u"长葛": "changge",
              u"怒江": "nujiang", u"平凉": "pl", u"益阳": "yiyang", u"北海": "bh", u"正定": "zd", u"宜春": "yichun", u"天水": "tianshui", u"阳泉": "yq", u"咸阳": "xianyang", u"自贡": "zg", u"云浮": "yf",
              u"东海": "donghai", u"安顺": "anshun", u"崇左": "chongzuo", u"丽江": "lj", u"拉萨": "lasa", u"阿里": "al", u"西安": "xa", u"汉中": "hanzhong", u"建湖": "jianhu", u"庄河": "pld",
              u"西宁": "xn", u"丽水": "lishui", u"喀什": "ks", u"驻马店": "zmd", u"玉树": "ys", u"铜川": "tc", u"莱芜": "lw", u"海门": "haimen", u"来宾": "lb", u"巴音郭楞": "bygl", u"昭通": "zt",
              u"达州": "dazhou", u"酒泉": "jq", u"张北": "zhangbei", u"濮阳": "puyang", u"芜湖": "wuhu", u"汕尾": "sw", u"阳江": "yj", u"明港": "mg", u"临猗": "linyixian", u"九江": "jj", u"抚州": "fuzhou",
              u"铁岭": "tl", u"枣庄": "zaozhuang", u"大理": "dali", u"鹤岗": "hegang", u"章丘": "zhangqiu", u"大同": "dt", u"宁国": "ningguo", u"银川": "yinchuan", u"毕节": "bijie", u"株洲": "zhuzhou",
              u"珠海": "zh", u"延边": "yanbian", u"西双版纳": "bn", u"忻州": "xinzhou", u"乌兰察布": "wlcb", u"巴中": "bazhong", u"张掖": "zhangye", u"济源": "jiyuan", u"佳木斯": "jms", u"泰州": "taizhou",
              u"韶关": "sg", u"淄博": "zb", u"神农架": "snj", u"鄂尔多斯": "erds", u"南平": "np", u"河池": "hc", u"黄山": "huangshan", u"唐山": "ts", u"白山": "baishan", u"蚌埠": "bengbu",
              u"南昌": "nc", u"吉林": "jl", u"锡林郭勒盟": "xl", u"鄂州": "ez", u"顺德": "sd", u"宣城": "xuancheng", u"兴安盟": "xam", u"滨州": "bz", u"徐州": "xz", u"阿克苏": "aks", u"慈溪": "cixi",
              u"巢湖": "ch", u"东营": "dy", u"南阳": "ny", u"寿光": "shouguang", u"马鞍山": "mas", u"惠州": "huizhou", u"百色": "baise", u"象山": "xiangshanxian", u"阿拉善盟": "alsm", u"长春": "cc",
              u"哈密": "hami", u"克孜勒苏": "kzls", u"眉山": "ms", u"嘉兴": "jx", u"克拉玛依": "klmy", u"宝鸡": "baoji", u"迪庆": "diqing", u"盐城": "yancheng", u"武夷山": "wuyishan", u"白银": "by",
              u"秦皇岛": "qhd", u"天门": "tm", u"启东": "qidong", u"昌都": "changdu", u"赤峰": "chifeng", u"沧州": "cangzhou", u"南京": "nj", u"舟山": "zhoushan", u"郑州": "zz", u"石狮": "shishi", u"宁德": "nd"}
    }
    return address_keywords_dict[city][area]

def education_keywords_dict(education_key):
    education_dict = {
        u'不限': '', u'高中以下': 'pve_5593_1', u'高中': 'pve_5593_2', u'中专/技校': 'pve_5593_3', u'大专': 'pve_5593_4', u'本科': 'pve_5593_5', u'硕士': 'pve_5593_6',\
        u'博士': 'pve_5593_7', u'MBA/EMBA': 'pve_5593_8'}

    return  education_dict[education_key]

def low_workage_dict(low_workage_key):
    workage_dict = {u'不限': '', u'1-2年': 'pve_5594_1', u'3-5年': 'pve_5594_2', u'6-10年': 've_5594_3', u'10年以上': 'pve_5594_4'}

    return workage_dict[low_workage_key]
def job_dict(job_key):
    job_dict = {
        u"供应商/采购质量管理": "qzzhiliangbaozhengqa", u"厨师助理/学徒": "qzzpxuetu", u"射频工程师": "qzyingjiangong", u"Helpdesk 技术支持": "qzxitonggcs",
         u"办事处/分公司/分支机构经理": "qzfengongsijingli", u"医药销售经理/主管": "qzxiaoshoujingli", u"市场分析/调研人员": "qzshichangdiaoyan", u"机场代表": "qzguojihuoyun",
         u"供应链经理": "qzgongyinglianguanli", u"市场通路经理/主管": "qzshichangzongjian", u"高中教师": "qzjiaoshi", u"建筑工程师": "qzjianzhugongchengshi", u"裁床": "qzcaijiangong",
         u"渠道/分销主管": "qzqudaojingli", u"汽车机构工程师": "qzqichedianzi", u"酒店/宾馆营销": "qzzpjiudianguanli", u"服装/纺织/皮革工艺师": "qzfangzhisheji", u"店长/卖场经理/楼面管理": "qzdianzhang",
         u"药品注册": "qzyiyaoyanfa", u"研究生": "qzgongwuyuanjs", u"商务经理": "qzshangwuzhuanyuan", u"保险代理/经纪人/客户经理": "qzbaoxian", u"专柜彩妆顾问(BA)": "qzcaizhuangpeixun",
         u"嵌入式软件开发(Linux/单片机/PLC/DSP…)": "qzqianruyingjian", u"宾客服务经理": "qzzpkefang", u"调研员": "qzzpgwysydw", u"物业管理经理/主管": "qzwuyejingli", u"工程/设备工程师": "qzshebeiguanli",
         u"选址拓展/新店开发": "qzdianzhang", u"标准化工程师": "qztixigcs", u"外汇交易": "qzjingjiren", u"金融产品经理": "qzwangzhanchanpin", u"收银主管/收银员": "qzshouying", u"前厅接待": "qzzpkefang",
         u"电力工程师/技术员": "qzdianzidianqigcs", u"理财顾问/财务规划师": "qzjinrong", u"资金专员": "qzrongzizhuanyuan", u"业务分析经理/主管": "qztouzifenxi", u"药库主任/药剂师": "qzyyyaokuzhuren",
         u"运输经理/主管": "qzwuliujingli", u"餐饮/娱乐领班/部长": "qzyulefwy", u"经销商": "qzqudaorenyuan", u"渠道/分销专员": "qzqudaorenyuan", u"外语教师": "qzyingyufanyi",
         u"IC验证工程师": "qzbantushejigcs", u"临床研究员": "qzyiliao", u"导购员": "qzcuxiao", u"理货员/陈列员/收货员": "qzlihuoyuan", u"产品/品牌主管": "qzwangzhanchanpin", u"兼职教师": "qzzpwudao",
         u"印刷排版/制版": "qzcbyishua", u"行政经理/主管/办公室主任": "qzxingzhengjingli", u"生产主管/督导/领班/组长": "qzshengchanzhuguan", u"安全防护": "qzanquanxiaofang",
         u"光源与照明工程": "qzzhaomingsheji", u"营运经理": "qzzpdudao", u"CNC工程师": "qzshukonggcs", u"文案/策划": "qzwenan", u"化妆师/造型师": "qzfaxingshi", u"运营经理": "qzpinpaijingli",
         u"运维总监": "qzxitonggcs", u"公关/媒介助理": "qzgongguanzhuanyuan", u"电池/电源开发": "qztongxindianyuan", u"服装/纺织设计总监": "qzfangzhisheji", u"项目总监": "qzxiangmuzongjian",
         u"行程管理/计调": "qzzpjidiao", u"SEO搜索引擎优化": "qzseoyouhua", u"面料辅料开发": "qzyangyigong", u"技术研发经理/主管": "qzjishuzongjian", u"ERP技术开发": "qzruanjiangong",
         u"培训生": "qzxsjiangshi", u"产品总监": "qzwangzhanchanpin", u"酒店/宾馆经理": "qzzpjiudianguanli", u"采购经理": "qzcaigouzhuli", u"组长/拉长": "qzshengchanzhuguan",
         u"媒介销售": "qzmeijiejingli", u"临床协调员": "qzyixuejianyan", u"企业文化/员工关系/工会管理": "qzxinzifuli", u"固废工程师": "qzwushuichuli", u"理科教师": "qzjiaoshi",
         u"汽车定损/车险理赔": "qzbaoxianheshi", u"汽车销售/经纪人": "qzqichexiaoshou", u"放映经理/主管": "qzfangyingyuan", u"美容顾问/化妆": "qzyymeirongzhengxing",
         u"汽车动力系统工程师": "qzqichejixie", u"房地产评估": "qzzcpinggu", u"业务跟单": "qzwaimaozhuanyuan", u"工厂经理/厂长": "qzchangzhang", u"技工": "qzqiangong",
         u"生鲜食品加工/处理": "qzshipinjiagong", u"文档工程师": "qzruanjiangong", u"清洁工": "qzzpzagong", u"志愿者/社会工作者": "qzzpgwysydw", u"工程造价师/预结算经理": "qzgongchengzhaojia",
         u"电子商务经理/主管": "qzdianzisw", u"供应商管理": "qzkaifagongying", u"服装/纺织/皮革跟单": "qzzpfangzhi", u"机构客户服务": "qzyyyiyuan", u"票务/订房服务": "qzzpdingpiao",
         u"基金管理": "qzzijinguanli", u"智能大厦/综合布线/安防/弱电": "qzbuxianruodian", u"需求工程师": "qzxuqiufenxi", u"软装设计师": "qzfuzhuangsheji", u"旅游产品销售": "qzlvyoucehua",
         u"健身房服务": "qzjianshenguwen", u"行长/副行长": "qzzhengquanjingli", u"船舶工程师": "qzchuanbozhizao", u"固定资产会计": "qzcaiwugw", u"电气工程师/技术员": "qzdianzidianqigcs",
         u"熟食加工": "qzshipinjiagong", u"投资银行业务": "qzyinhangjingli", u"制造工程师": "qzzhuangpeigongyi", u"公路桥梁预算师": "qzgongluqiaoliang", u"裁缝印纺熨烫": "qzfengrengong",
         u"营运主管": "qzzpdudao", u"技术文员/助理": "qzwenziluru", u"综合业务专员": "qzyinhangyewu", u"建筑制图/模型/渲染": "qzshejizhitu", u"个人业务客户经理": "qzyinhangjingli",
         u"涉外咨询师": "qzyinminzixun", u"信息技术专员": "qzjszhuanyuan", u"语音/视频开发工程师": "qzcadsheji", u"自动控制工程师/技术员": "qzzhizaogongchengshi", u"驯兽师/助理驯兽师": "qzxumushi",
         u"专业培训师": "qzjypeixunshi", u"服装/纺织设计": "qzfuzhuangsj", u"广告项目管理": "qzfengmiansj", u"咨询热线/呼叫中心服务人员": "qzkehuzixun", u"咨询员": "qzdaoyiyuan",
         u"会计文员": "qzchuna", u"包装工程师": "qzbaozhuanggcs", u"生产计划/物料管理(PMC)": "qzjihuatiaodu", u"信审核查": "qzrenzhengyuan", u"售前/售后技术支持主管": "qzxiaoshougongchengshi",
         u"职业技术教师": "qzjiaoshi", u"电子工程师/技术员": "qzdianzidianqigcs", u"院校教务管理人员": "qzjiaowu", u"乘务员": "qzkongcheng", u"广告客户经理": "qzzpkehuzhuguan",
         u"场长(农/林/牧/渔业)": "qznongchangzhu", u"电声/音响工程师/技术员": "qzdengguangshi", u"投资/基金项目经理": "qzjinrong", u"规划设计经理": "qzgongyigcs", u"安防主管": "qzjianzhuanfang",
         u"知识产权/专利/商标": "qzzhuanliguwen", u"家用电器/数码产品研发": "qzdianzidianqiwx", u"列车/地铁车长": "qzditiesiji", u"企业/业务发展经理": "qzzpqiyecehua", u"船员": "qzshuishou",
         u"售前/售后技术支持工程师": "qzjishuzhichi", u"宴会管理": "qzjiudianjl", u"国内贸易人员": "qzgongyinglianguanli", u"组织发展(OD)": "qzshengchanguanli", u"生产文员": "qzwenziluru",
         u"规划与设计": "qzgongyigcs", u"招投标管理": "qzgongchengzhaojia", u"建筑设备工程师": "qzshigongguanli", u"产品/品牌经理": "qzpinpaijingli", u"房地产项目管理": "qzjianzhugongcheng",
         u"工业/产品设计": "qzhuagongguanli", u"贸易/外贸经理/主管": "qzwaimaojingli", u"品质经理": "qzzhiliangbaozhengqa", u"司仪": "qzzphunlicehua", u"总监/部门经理": "qzxingzhengjingli",
         u"经纪业务": "qzfangdichan", u"锅炉工程师/技师": "qzgulugong", u"房地产中介/交易": "qzfangdichan", u"证券分析师": "qzcaopanshou", u"冲压工程师/技师": "qzzhuangpeijishi",
         u"船长/副船长": "qzshuishou", u"可靠度工程师": "qztongxinwuxian", u"冶金工程师": "qzhuagongshi", u"清算人员": "qzchuna", u"半导体技术": "qzjichengdianlu", u"培训/课程顾问": "qzjyzhaosheng",
         u"饲养员": "qzyangzhi", u"EHS管理": "qzehsguanli", u"高级物业顾问/物业顾问": "qzwuyejingli", u"客服主管(非技术)": "qzkefuzongjian", u"兼职": "qzjiajiaolaoshi", u"零售客户服务": "qzdianzhang",
         u"渠道/分销总监": "qzqudaojingli", u"注塑工程师/技师": "qzmojugong", u"家政服务/保姆": "qzbaomuxin", u"电子软件开发(ARM/MCU...)": "qzqianruruanjian", u"财务分析经理/主管": "qzcaiwujingli",
         u"质量管理/验货员(QA/QC)": "qzzhijianyuan", u"国内贸易经理": "qzshangwuzhuanyuan", u"供应链主管/专员": "qzwuliuzongjian", u"土建造价工程师": "qzshizhenggc",
         u"化工实验室研究员/技术员": "qzhuagongshi", u"电子商务总监": "qzdianzisw", u"储备干部": "qzchubeijingli", u"售前/售后技术支持经理": "qzxiaoshougongchengshi", u"打稿机操作员": "qzyinshuajizhang",
         u"寻呼员/话务员": "qzshujvtongxin", u"固定收益业务": "qzzijinguanli", u"公路/桥梁/港口/隧道工程": "qzshuiligc", u"大学教授": "qzjiaoshi", u"记者": "qzjizhe", u"电分操作员": "qztiaomoshi",
         u"飞机机长/副机长": "qzfeijijiashi", u"公司业务客户经理": "qzkehujingli", u"铸造/锻造工程师/技师": "qzmojugong", u"营业部大堂经理": "qzdatangjingli", u"建筑工程安全管理": "qzshigongguanli",
         u"汽车项目管理": "qzqichesheji", u"原画师": "qzyouxiyuanhua", u"培训产品开发": "qzjiaoyukaifa", u"夹具工程师/技师": "qzzhuangpeijishi", u"ERP实施顾问": "qzruanjianshishi",
         u"化工技术应用/化工工程师": "qzhuaxueyingyong", u"工艺品/珠宝设计鉴定": "qzgongyisheji", u"电脑操作员/打字员": "qzzpzagong", u"房地产项目招投标": "qzfangdichankaifa", u"文科教师": "qzjiaoshi",
         u"飞机维修机械师": "qzfeijiweixiu", u"清洁服务人员": "qzzpkefang", u"安装造价工程师": "qzshizhenggc", u"策略发展总监": "qzzpqiyecehua", u"环境影响评价工程师": "qzhuanbaoshi",
         u"切割技工": "qzmaohangong", u"首席财务官 CFO": "qzshouxicaiwu", u"广告客户主管/专员": "qzmeijiejingli", u"工程/设备主管": "qzshebeiguanli", u"药品生产/质量管理": "qzzhiliangbaozhengqa",
         u"药品市场推广主管/专员": "qzyiyaodaibiao", u"生产经理/车间主任": "qzshengchanjingli", u"电子技术研发工程师": "qzyingjiangong", u"功能测试": "qzceshigongchengshi", u"餐饮/娱乐管理": "qzyulefwy",
         u"软件UI设计师/工程师": "qzjiemiansheji", u"客服总监(非技术)": "qzkefuzongjian", u"建筑设计师": "qzfangwusj", u"小学教师": "qzjiaoshi", u"物业机电工程师": "qzjxjixiegongchengshi",
         u"契约管理": "qzbaoxianheshi", u"促销经理": "qzcuxiao", u"网络推广经理/主管": "qzwangluoxiaoshouyuan", u"图书管理员/资料管理员": "qzziliao", u"生产设备管理": "qzgcsbguanli",
         u"绩效考核专员/助理": "qzxingzhengzhuanyuan", u"成本经理/成本主管": "qzzpchengben", u"首席技术执行官CTO/首席信息官CIO": "qzshouxiyunying", u"首席执行官CEO/总裁/总经理": "qzzpzongcai",
         u"咨询项目管理": "qzzixunshi", u"医疗器械维修人员": "qzyiliaoqixie", u"空乘人员": "qzkongcheng", u"运维开发": "qzxitonggcs", u"运维经理": "qzxitonggcs", u"多媒体/游戏开发工程师": "qzyouxisheji",
         u"医疗器械注册": "qzyiyaoyanfa", u"报关与报检": "qzdanzhengyuan", u"船务/空运陆运操作": "qzjizhuangxiangyw", u"输电线路工程师": "qzguangfuxitong",
         u"质量管理/测试工程师(QA/QC工程师)": "qzzhijianyuan", u"产品规划工程师": "qzgongyigcs", u"房地产销售经理/主管": "qzxiaoshoujingli", u"中国方言翻译": "qzhanyu",
         u"项目执行/协调人员": "qzjihuatiaodu", u"UI设计师/顾问": "qzjiaohusheji", u"计量工程师": "qzjxyiqigongcheng", u"飞行器设计与制造": "qzfeijizhizao",
         u"晒版/拼版/装订/烫金技工": "qzzhuangdingyuan", u"市场/营销/拓展专员": "qzshichangzhuanyuan", u"房产项目配套工程师": "qzzpfangchankefu", u"银行卡、电子银行业务推广": "qzyinhangyewu",
         u"首席人力资源官CHO/HRVP": "qzshouxiyunying", u"系统分析员": "qzxitongjichengfenxi", u"中学教师": "qzjiaoshi", u"演员/模特/主持人": "qzwtzhuchiren", u"能源/矿产项目管理": "qztianranqijishu",
         u"广告客户总监/副总监": "qzwuyejingli", u"4S店经理/维修站经理": "qzqichexiaoshou", u"业务跟单经理": "qzkehujingli", u"采购材料、设备质量管理": "qzshebeiguanli",
         u"综合业务经理/主管": "qzyinhangjingli", u"传菜主管/传菜员": "qzchuancaiyuan", u"薪资福利专员/助理": "qzzhaopinzhuanyuan", u"面料辅料采购": "qzyangyigong",
         u"质量管理/测试经理(QA/QC经理)": "qzzhiliangguanli", u"网站维护工程师": "qzwangzhangoujia", u"外语培训师": "qzyingyufanyi", u"医疗器械生产/质量管理": "qzyyyiyuan",
         u"增值产品开发工程师": "qzbaoxiankaifa", u"实习生": "qzzpxuetu", u"嵌入式硬件开发(主板机…)": "qzqianruyingjian", u"医药技术研发人员": "qzkeyanyuan", u"猎头/人才中介": "qzlietouguwen",
         u"中专/职校生": "qzxumushi", u"保险业务经理/主管": "qzbaoxianjchanpin", u"维修经理/主管": "qzyangzhizhuguan", u"建筑机电工程师": "qzjxjixiegongchengshi", u"物业管理专员/助理": "qzwuyejingli",
         u"医疗技术人员": "qzyiliaoyanfa", u"市场企划专员": "qzqihuajingli", u"轨道交通工程师/技术员": "qzshizhenggc", u"汽车质量管理": "qzzhiliangbaozhengqa", u"实验室负责人/工程师": "qzkeyanguanli",
         u"平面设计经理/主管": "qzsheji", u"情报信息分析人员": "qzshichangdiaoyan", u"展览/展示/店面设计": "qzzhanshizhuanghuang", u"绘画": "qzyinmei", u"贸易/外贸专员/助理": "qzwaimaozhuanyuan",
         u"环境/健康/安全工程师（EHS）": "qzhjguanli", u"交互设计师": "qzjiemiansheji", u"钢结构工程师": "qzjiegoutongcheng", u"咨询总监": "qzzixunjingli", u"成本总监": "qzzpchengben",
         u"西点师/面包糕点加工": "qzmiandianshi", u"首席运营官COO": "qzshouxiyunying", u"计算机辅助设计工程师": "qzdianzikaifa", u"客户总监": "qzzpkehuzhuguan", u"搬运工": "qzbanyungong",
         u"物业招商/租赁/租售": "qzzpfangchankefu", u"财务主管/总帐主管": "qzcaiwuzhuli", u"空调工/电梯工/锅炉工": "qzgulugong", u"FAE 现场应用工程师": "qzfaeyingyong", u"兽医": "qzchongwuyisheng",
         u"渠道/分销经理": "qzqudaojingli", u"电话采编": "qzjizhe", u"物业设施管理人员": "qzzonghewuyeweixiugong", u"环境/健康/安全经理/主管（EHS）": "qzhjlvhua", u"叉车工": "qzchachegong",
         u"办事处首席代表": "qzshouxiyunying", u"发型助理/学徒": "qzfaxingshi", u"行政主厨/厨师长": "qzcanguan", u"网站营运经理/主管": "qzwangzhanyunying", u"成本经理": "qzzpchengben",
         u"美术编辑": "qzmeishuzhidao", u"汽车修理人员": "qzqichewx", u"保镖": "qzbaoanl", u"市场通路专员": "qzqudaorenyuan", u"项目管理": "qzjianzhugongcheng", u"产品管理": "qzxiangmuzongjian",
         u"个人业务部门经理/主管": "qzxiaoshoujingli", u"活动执行": "qzzptaobaocehua", u"动画/3D设计": "qzduomeiti", u"公务员": "qzzpgwysydw", u"专科医生": "qzhushi",
         u"市场/营销/拓展总监": "qzshichangzhuanyuan", u"作家/撰稿人": "qzbianji", u"品类经理": "qzpinleiguanli", u"促销员/导购": "qzcuxiao", u"体育运动教练": "qzzpyouyong",
         u"客服经理(非技术)": "qzkefuzongjian", u"资金经理/主管": "qzcaiwujingli", u"助理业务跟单": "qzzpkehuzhuguan", u"水工/木工/漆工": "qzmugong", u"产品工艺/制程工程师": "qzjsgysheji",
         u"运维工程师": "qzjishuzhichi", u"硬件测试": "qzyingjiangong", u"合规主管/专员": "qzheguiguanli", u"医药学检验": "qzyixuejianyan", u"导游/旅行顾问": "qzdyao",
         u"建筑工程管理/项目经理": "qzshigongguanli", u"培训督导": "qzzpdudao", u"给排水/暖通工程": "qzgeipaishui", u"经纪人/星探": "qzbaoxian", u"金融/经济研究员": "qzzhengquanfenxi",
         u"销售工程师": "qzxiaoshouyuan", u"精密机械": "qzzpjixiegongcheng", u"水处理工程师": "qzhuanbaoshi", u"医药技术研发管理人员": "qzshengwugongcheng", u"电焊工/铆焊工": "qzmaohangong",
         u"人力资源信息系统专员": "qzzhaopinzhuanyuan", u"房地产项目/开发/策划主管/专员": "qzfangdichankaifa", u"网站营运总监": "qzwangzhanyunying", u"信贷管理": "qzzichanpinggu",
         u"房地产项目运营": "qzfangdichankaifa", u"客服专员/助理(非技术)": "qzkefuzhuanyuan", u"编辑": "qzwangzhanyingyun", u"房地产销售人员": "qzfangdichan", u"列车/地铁司机": "qzditiesiji",
         u"规划设计总监": "qzgongyigcs", u"产品/品牌专员": "qzwangzhanchanpin", u"客户关系经理/主管": "qzdakehujingli", u"人力资源伙伴(HRBP)": "qzlietouguwen", u"薪资福利经理/主管": "qzxinzifuli",
         u"信息技术经理/主管": "qzfengongsijingli", u"保险产品开发/项目策划": "qzbaoxiankaifa", u"导演/编导": "qzyingshicehua", u"业务分析专员/助理": "qzshichangdiaoyan", u"瘦身顾问": "qzmeirongguwen",
         u"专业顾问": "qzzixunshi", u"三维/3D设计/制作": "qzsanweisheji", u"会计": "qzcaiwuzhuli", u"Flash设计/开发": "qzwangzhanmeigong", u"视觉设计师": "qztexiaosheji", u"预定员": "qzzpyudingyuan",
         u"物料主管/专员": "qzwuliaoguanli", u"理货员": "qzlihuoyuan", u"绩效考核经理/主管": "qzxingzhengjingli", u"体系工程师/审核员": "qztixigcs", u"企业秘书/董事会秘书": "qzmishu",
         u"预结算员": "qzxinyongjiesuan", u"VIP专员": "qzvipzhuanyuan", u"行业研究": "qzzhengquanfenxi", u"核力/火力工程师": "qzhediangong", u"售后服务/客户服务": "qzshouhoufuwu",
         u"股票/期货操盘手": "qzcaopanshou", u"互联网软件开发工程师": "qzruanjiangong", u"自动化测试": "qzceshigongchengshi", u"艺术/设计总监": "qzwutaimeishu", u"项目工程师": "qzxiangmuzongjian",
         u"大客户销售管理": "qzkehuguanxi", u"医院管理人员": "qzyiliao", u"农艺师": "qznongyishi", u"促销主管/督导": "qzzpdudao", u"药品市场推广经理": "qzyiyaodaibiao", u"商务助理": "qzshangwuzhuanyuan",
         u"玩具设计": "qzgongyisheji", u"兼职店员": "qzyingyeyuan", u"业务拓展主管/经理": "qzkehujingli", u"游戏策划师": "qzyouxicehua", u"质量管理/测试主管(QA/QC主管)": "qzzhiliangguanli",
         u"调酒师/侍酒师/吧台员": "qztiaojiushi", u"高级业务跟单": "qzwaimaozhuanyuan", u"网站编辑": "qzwangzhanyingyun", u"销售代表": "qzxiaoshouyuan", u"统计员": "qztongjiyuan",
         u"智能大厦/综合布线/安防/弱电": "qzzhuangpeigongyi", u"讲师/助教": "qzjiaoshi", u"咨询经理": "qzzixunjingli", u"软件工程师": "qzruanjiangong", u"高级软件工程师": "qzruanjiangong",
         u"电子商务专员": "qzdianzisw", u"游戏界面设计师": "qzjiemiansheji", u"物流总监": "qzwuliuzongjian", u"媒介专员": "qzshichangcehuagongguanmeijie", u"汽车底盘/总装工程师": "qzqczozhuang",
         u"总工程师/副总工程师": "qzzonggongchengshi", u"电信网络工程师": "qzdianxinwangluo", u"律师助理": "qzlvshizhuli", u"行政总监": "qzxingzhengzongjian", u"列车设计与制造": "qzliechezhizao",
         u"法语翻译": "qzfayufanyi", u"销售经理": "qzxiaoshoujingli", u"保安人员": "qzbaoanl", u"行政专员/助理": "qzxingzhengzhuanyuan", u"电信交换工程师": "qzdianxinjiaohuan",
         u"废气处理工程师": "qzwushuichuli", u"成本管理员": "qzzpchengben", u"电路工程师/技术员(模拟/数字)": "qzdidianqigongchengshi", u"人事总监": "qzrenshizongjian", u"审计专员/助理": "qztongjishenji",
         u"电脑放码员": "qzfangmayuan", u"科研管理人员": "qzkeyanguanli", u"理疗师": "qzyyliliaoshi", u"厨师/面点师": "qzmiandianshi", u"财务顾问": "qzcaiwugw", u"全科医生": "qzyiliao",
         u"护士/护理人员": "qzhushi", u"海关事务管理": "qzhaiguanshiwu", u"市政工程师": "qzshizhenggc", u"泰语翻译": "qzjyxiaoyuzhongfanyi", u"广告创意/设计主管/专员": "qzshejichuangyi",
         u"校长": "qzxiaozhang", u"保险理赔": "qzbaoxianheshi", u"施工员": "qzshigongyuan2", u"进出口/信用证结算": "qzxinyongjiesuan", u"特效设计师": "qztexiaosheji", u"版图设计工程师": "qzbantushejigcs",
         u"防损员/内保": "qzfangsunyuan", u"培训讲师": "qzjypeixunshi", u"故障分析工程师": "qzguzhangfenxi", u"美容助理/见席美容师": "qzmeirongshi", u"汽车/摩托车工程师": "qzqichewx",
         u"通信技术工程师": "qztongxinwuxian", u"机械工程师": "qzzpjixiegongcheng", u"投诉专员": "qztousuzhuanyuan", u"岩土工程": "qzyantugc", u"软件UI设计师/工程师": "qzjiaohusheji",
         u"数据库工程师/管理员": "qzshujukukaifa", u"财务分析员": "qzcaiwufenxi", u"培训经理/主管": "qzpeixunjingli", u"银行柜员": "qzyinhangkuaiji", u"政府事务管理": "qzzhengfushiwu",
         u"后勤": "qzhouqin", u"矿产勘探/地质勘测工程师": "qzdizhikancha", u"列车维修/保养": "qzliecheweixiu", u"家教": "qzjiajiaolaoshi", u"财务/会计助理": "qzcaiwuzhuli",
         u"涂料研发工程师": "qztuliaoyanfa", u"前台接待/总机/接待生": "qzqiantai", u"物流主管": "qzwuliujingli", u"测绘/测量": "qzcehuiceliang", u"营养师": "qzyyyingyangshi", u"合同管理": "qzjzhetong",
         u"买手": "qzmaishou", u"市场/营销/拓展主管": "qzshichangzhuanyuan", u"葡萄牙语翻译": "qzputaoyayu", u"经理助理/秘书": "qzmishu", u"激光/光电子技术": "qzjiguangjishu",
         u"儿科医生": "qzchankeyisheng", u"俄语翻译": "qzeyufanyi", u"材料工程师": "qzcailiaogcs", u"按摩/足疗": "qzbaojiananmozuliao", u"商务主管/专员": "qzshangwuzhuanyuan",
         u"临床数据分析员": "qzlinchuangshujv", u"税务专员/助理": "qzshuiwuzhuanyuan", u"医药销售代表": "qzyiyaodaibiao", u"礼仪/迎宾": "qzwtliyi", u"汽车设计工程师": "qzqichesheji",
         u"幕墙工程师": "qzmuqiang", u"采购员": "qzcaigouyuan", u"保险精算师": "qzbaoxianjingsuan", u"护理主任/护士长": "qzhushizhang", u"人事主管": "qzrenshizhuguan", u"培训策划": "qzpeixuncehua",
         u"配色技术员": "qzpeisejishu", u"纸样师/车板工": "qzzhiyangshi", u"科研人员": "qzkeyanyuan", u"市场企划经理/主管": "qzqihuajingli", u"调度员": "qzdiaodu", u"养殖部主管": "qzyangzhizhuguan",
         u"客户主管/专员": "qzzpkehuzhuguan", u"货运代理": "qzhuoydaili", u"结构工程师": "qzjiegoutongcheng", u"保险培训师": "qzbaoxianpeixun", u"畜牧师": "qzxumushi",
         u"网站架构设计师": "qzwangzhangoujia", u"韩语/朝鲜语翻译": "qzhanyu", u"人事助理": "qzzhaopinjingli", u"法务助理": "qzlfawurenyuan", u"合规经理": "qzheguiguanli",
         u"二手车评估师": "qzqcpinggushi", u"行李员": "qzxingliyuan", u"石油天然气技术人员": "qztianranqijishu", u"医疗器械研发": "qzyiliaoyanfa", u"板房/楦头/底格出格师": "qzchugeshi",
         u"心理医生": "qzyyxinliyisheng", u"汽车修理工": "qzqichexiuli", u"园艺/园林/景观设计": "qzfangwusj", u"市场助理": "qzyingxiaozhuanyuan", u"技术总监/经理": "qzjishuzongjian",
         u"出版/发行": "qzcbchuban", u"电子/电器维修工程师/技师": "qzdianzidianqiwx", u"地勤人员": "qzdiqinyuan", u"技术支持/维护工程师": "qzjishuzhichi", u"拍卖/担保/典当业务": "qzdanbaopaimai",
         u"宠物护理/美容": "qzchongwumr", u"仪器/仪表/计量分析师": "qzjxyiqigongcheng", u"动物营养/饲料研发": "qzsiliaoyanfa", u"配音员": "qzpeiyin", u"资产评估/分析": "qzzcpinggu",
         u"工业工程师": "qzgongyegcs", u"融资总监": "qzrongzizhuanyuan", u"公共卫生/疾病控制": "qzjikong", u"总编/副总编": "qzcbzhubian", u"招聘经理/主管": "qzzhaopinzhuguan",
         u"工程监理": "qzgongchengjianli", u"仓库管理员": "qzcangku", u"摄影师/摄像师": "qzwtxieying", u"生产总监": "qzshengchanzongjian", u"救生员": "qzjiushengyuan", u"水质检测员": "qzshuizhijiance",
         u"焊接工程师/技师": "qzzhuangpeijishi", u"审计经理/主管": "qzshenjijingli", u"其他语种翻译": "qzjyxiaoyuzhongfanyi", u"美容整形师": "qzyymeirongzhengxing", u"律师/法律顾问": "qzlvshizhaopin",
         u"司机": "qzshangwujiaochesiji", u"房地产项目/开发/策划经理": "qzfangdichankaifa", u"资产/资产管理": "qzzijinguanli", u"网店店长/客服": "qzzptaobaodianzhang", u"健身顾问/教练": "qzjianshenguwen",
         u"企业策划人员": "qzzpqiyecehua", u"平面设计师": "qzsheji", u"建筑工程验收": "qzjianzhuyanshou", u"活动策划": "qzzptaobaocehua", u"音乐/美术教师": "qzyinmei", u"电话销售": "qzdianhuaxiaoshou",
         u"保险内勤": "qzbaoxianneiqin", u"数码直印/菲林输出": "qzfeilin", u"空调/热能工程师": "qzrenenggong", u"移动通信工程师": "qzyidongtongxin", u"资料员": "qzziliao", u"日语翻译": "qzriyufanyi",
         u"财务经理": "qzcaiwuzongjian", u"房地产投资分析": "qztouzifenxi", u"投资者关系": "qztouziguanxi", u"工程/设备经理": "qzshebeiguanli", u"制作执行": "qzguanggaozhixing",
         u"仓库经理/主管": "qzcangkujingli", u"产品专员": "qzwangzhanchanpin", u"网络推广专员": "qzwangluotuiguang", u"影视策划/制作人员": "qzyingshicehua", u"塑料工程师": "qzsuliaogc",
         u"化验员": "qzhuayan", u"印刷机械机长": "qzyinshuajizhang", u"音效师": "qzwtluying", u"手机应用开发工程师": "qzshoujiruanjian", u"单证员": "qzdanzhengyuan", u"仿真应用工程师": "qzfangzhengc",
         u"彩妆培训师": "qzcaizhuangpeixun", u"医疗器械销售代表": "qzyiliaoqixie", u"高级建筑工程师/总工": "qzjianzhugongchengshi", u"环保检测": "qzhuanbaojiance", u"维修工程师": "qzweixiugong",
         u"验光师": "qzyanguangshi", u"餐饮/娱乐服务员": "qzyulefwy", u"调墨技师": "qztiaomoshi", u"系统管理员/网络管理员": "qzwangluogongchengshi", u"网络信息安全工程师": "qzwangluoanquan",
         u"普工/操作工": "qzzhizaogongchengshi", u"放映员": "qzfangyingyuan", u"英语翻译": "qzyingyufanyi", u"店员/营业员": "qzyingyeyuan", u"系统工程师": "qzxitonggcs", u"储备经理人": "qzchubeijingli",
         u"测试经理": "qzceshigongchengshi", u"快递员": "qzsudiyuan", u"数据通信工程师": "qzshujvtongxin", u"合伙人": "qzhehuoren", u"后期制作": "qzsanweisheji", u"脚本开发工程师": "qzjiaobenkaifa",
         u"幼教": "qzyouerjiaoshi", u"培训助理": "qzpeixunzhuli", u"项目主管": "qzxiangmuzongjian", u"水利/港口工程技术": "qzshuiligc", u"网站营运专员": "qzwangzhanyunying", u"模具工": "qzmojugong",
         u"证券/期货/外汇经纪人": "qzjingjiren", u"楼宇自动化": "qzlouyuzidonghua", u"电工": "qzdianzi", u"美术指导": "qzmeishuzhidao", u"采购助理": "qzcaigouzhuli", u"美甲师": "qzmeitishi",
         u"车工/磨工/铣工/冲压工/锣工": "qzshukongjichuang", u"针灸、推拿": "qzzptuina", u"出纳员": "qzchuna", u"物料经理": "qzwuliaoguanli", u"会务/会展专员": "qzhuiwujingli", u"多媒体设计": "qzduomeiti",
         u"硬件工程师": "qzyingjiangong", u"家具/家居用品设计": "qzjiajusj", u"采购总监": "qzcaigouguanli", u"房地产资产管理": "qzfanchanguanli", u"物业维修人员": "qzweixiugongchengshi",
         u"保险客户服务/续期管理": "qzxuqiguanli", u"性能测试": "qzqcanquanxingneng", u"销售行政经理/主管": "qzxingzhengjingli", u"瑜伽/舞蹈老师": "qzzpwudao", u"网站策划": "qzwangzhancehua",
         u"机电工程师": "qzjxjixiegongchengshi", u"无线通信工程师": "qzwuxiantongxin", u"公关主管": "qzgongguanjingli", u"美容导师": "qzzpmeirongdaoshi", u"钳工/机修工/钣金工": "qzqiangong",
         u"零配件销售": "qzlingjian", u"通信电源工程师": "qztongxindianyuan", u"茶艺师": "qzchayi", u"有线传输工程师": "qzyouxianchuanshu", u"光伏技术工程师": "qzguangfuxitong",
         u"质量检验员/测试员": "qzzhijianyuan", u"税务经理/税务主管": "qzshuiwujingli", u"排版设计": "qzcbyishua", u"物流专员/助理": "qzmaoyi", u"爆破工程师": "qzbaopogong",
         u"总裁助理/总经理助理": "qzzongcaizhuli", u"楼面经理": "qzzpjingli", u"大堂经理": "qzdatangjingli", u"认证工程师/审核员": "qzrenzhengyuan", u"工程/机械绘图员": "qzshejizhitu",
         u"招聘专员/助理": "qzzhaopinzhuanyuan", u"集成电路IC设计/应用工程师": "qzjichengdianlu", u"环保工程师": "qzhuanbaoshi", u"区域销售总监": "qzxiaoshouzongjian", u"德语翻译": "qzdeyufanyi",
         u"医药招商": "qzyiyaozhaoshang", u"食品/饮料研发": "qzshipinyanfa", u"生物工程/生物制药": "qzshengwugongcheng", u"技术研发工程师": "qzzpyanfa", u"风险控制": "qzfengxiankongzhi",
         u"团购业务员": "qztuangouxiaoshou", u"副总经理/副总裁": "qzfuzongcai", u"变压器与磁电工程师": "qzcidiangong", u"投资/理财顾问": "qzjinrong", u"意大利语翻译": "qzyidaliyu",
         u"系统架构设计师": "qzxitongjichengfenxi", u"造纸研发": "qzzaozhiyanfa", u"签证专员": "qzqianzheng", u"汽车电子工程师": "qzqichedianzi", u"气动工程师": "qzqidonggcs",
         u"客房服务员/楼面服务员": "qzzpkefang", u"区域销售经理": "qzquyuxiaoshou", u"发型师": "qzfaxingshi", u"化妆品研发": "qzhzpyanfa", u"网页设计/制作/美工": "qzwangzhanmeigong",
         u"公关专员": "qzgongguanzhuanyuan", u"西班牙语翻译": "qzxibanyayu", u"打样/制版": "qzfuzhuangdayang", u"销售助理": "qzxiaoshouzhuli", u"客户经理/主管": "qzkehujingli",
         u"高级客户经理/客户经理": "qzdakehujingli", u"包装设计": "qzbaozhuangsheji", u"化学分析测试员": "qzhuaxueceshi", u"供应商开发": "qzkaifagongying", u"媒介主管": "qzmeijiejingli",
         u"结构/土木/土建工程师": "qzjiegoutumu", u"集装箱业务": "qzjizhuangxiangyw", u"开发报建专员": "qzkaifajianbao", u"校对/录入": "qzjiaoduiy", u" 板房/楦头/底格出格师":"qzchugeshi",
		 u"装配工程师 / 技师": "qzzhuangpeijishi", u"软件测试": "qzyingjiancs", u"培训专员/助理/培训师": "qzpeixunzhuanyuan", u"技术支持/维护经理": "qzjishuzhichi", u"网络推广总监": "qzwangluotuiguang",
		 u"汽车装配工艺工程师": "qzzhuangpeigongyi", u"法务经理": "qzlfawurenyuan", u"销售行政专员/助理": "qzxingzhengzhuanyuan", u"公关经理": "qzgongguanjingli", u"预定部主管": "qzxiaoshoujingli",
		 u"汽车安全性能工程师": "qzqcanquanxingneng", u"会务/会展经理": "qzhuiwujingli", u"销售总监": "qzxiaoshouzongjian", u"销售主管": "qzxiaoshoujingli", u"高级硬件工程师": "qzyingjiangong",
		 u"开发报建经理": "qzkaifajianbao", u"手机软件开发工程师": "qzshoujiruanjian", u"项目经理": "qzxiangmuzongjian", u"网络工程师": "qzdianxinwangluo", u"中医科医生": "qzyiliao",
		 u"水利/水电工程师": "qzshuiligc", u"保险核保": "qzbaoxianheshi", u"大学/大专应届毕业生": "qzjiaowu", u"外科医生": "qzyiliao", u"软件测试": "qzceshigongchengshi",
		 u"麻醉医生": "qzmazuishi", u"融资专员": "qzrongzizhuanyuan", u"客户代表": "qzzpkehuzhuguan", u"项目经理/主管": "qzxiangmuzongjian", u"市场/营销/拓展经理": "qzshichangzhuanyuan",
		 u"保安经理": "qzbaoanl", u"牙科医生": "qzyiliao", u"室内设计": "qzsheji", u"采购主管": "qzcaigouguanli", u"平面设计总监": "qzsheji", u"安全员": "qzhouqin",
		 u"财务总监": "qzcaiwuzongjian", u"物流经理": "qzwuliujingli", u"装配工程师/技师": "qzzhuangpeijishi", u"会务/会展主管": "qzhuiwujingli", u"模具工程师": "qzmojugong",
		 u"人事经理": "qzrenshizhuguan", u"人事专员": "qzzhaopinjingli", u"广告创意总监": "qzshejichuangyi", u"测试员": "qzzpceshi", u"系统测试": "qzceshigongchengshi",
		 u"放射科医师": "qzyiliao", u"广告创意/设计经理": "qzshejichuangyi", u"开发报建": "qzkaifajianbao", u"融资经理/融资主管": "qzrongzizhuanyuan", u"测试工程师": "qzceshigongchengshi",
		 u"音效设计师": "qzwtluying", u"阿拉伯语翻译": "qzalaboyu", u"工艺工程师": "qzjsgysheji", u"大客户销售": "qzdakehujingli", u"产品经理/主管": "qzwangzhanchanpin",
		 u"内科医生": "qzyiliao", u"医疗器械销售经理/主管": "qzyiliaoqixie", u"系统集成工程师": "qzxitonggcs", u"管家部经理/主管": "qzzpjiudianguanli", u"供应链总监": "qzgongyinglianguanli",
		 u"会计经理/会计主管": "qzcaiwuzhuli", u"光伏系统工程师": "qzguangfuxitong", u"公司业务部门经理/主管": "qzxiangmuzongjian", u"法务主管/专员": "qzlfawurenyuan",
		 u"团购经理/主管": "qztuangouxiaoshou", u"媒介经理": "qzmeijiejingli", u"医疗器械市场推广": "qzyiliaoqixie"
    }

    return job_dict[job_key]
