#-*-coding: utf-8-*-

def address(city,area):
    address_keywords_dict = {
        'bj': {u"北京":"", u"石景山": "180", u"丰台": "179", u"大兴": "182", u"北京周边": "103680", u"顺义": "184", u"朝阳": "174", u"海淀": "173", u"平谷": "189", u"宣武": "178", u"房山": "181",
               u"崇文": "177", u"西城": "176", u"通州": "183", u"昌平": "185", u"怀柔": "187", u"燕郊": "3283", u"东城": "175", u"延庆": "188", u"门头沟": "190", u"密云": "186"},
        'tj': {u"天津":"",u"蓟县": "703", u"红桥": "691", u"东丽": "695", u"河西": "688", u"南开": "689", u"滨海新区": "103825", u"开发区": "704", u"河东": "687", u"河北": "690", u"西青": "696",
               u"宝坻": "700", u"北辰": "698", u"宁河": "701", u"和平": "686", u"塘沽": "692", u"大港": "694", u"汉沽": "693", u"津南": "697", u"静海": "702", u"武清": "699"},
        'sh': {u"上海":"", u"静安": "195", u"金山": "204", u"嘉定": "202", u"宝山": "201", u"黄浦": "191", u"普陀": "196", u"虹口": "198", u"松江": "205", u"浦东": "203", u"南汇": "207",
               u"奉贤": "208", u"闵行": "200", u"青浦": "206", u"徐汇": "193", u"崇明": "209", u"卢湾": "192", u"上海周边": "210", u"杨浦": "199", u"闸北": "197", u"长宁": "194"},
        'cq': {u"重庆":"", u"渝北": "2861", u"双桥": "2860", u"大足": "2875", u"潼南": "2873", u"九龙坡": "2856", u"巴南": "2862", u"城口": "2879", u"万盛": "2859", u"巫溪": "2888", u"铜梁": "2874",
               u"万州": "2863", u"南川": "2871", u"奉节": "2886", u"垫江": "2881", u"北碚": "2858", u"黔江": "2865", u"开县": "2884", u"酉阳": "2891", u"綦江": "2872", u"彭水": "2892",
               u"梁平": "2878", u"秀山": "2890", u"武隆": "2882", u"涪陵": "2864", u"渝中": "2852", u"沙坪坝": "2855", u"长寿": "2866", u"云阳": "2885", u"两江新区": "3622", u"璧山": "2877",
               u"合川": "2869", u"江北": "2854", u"忠县": "2883", u"大渡口": "2853", u"其他市县": "2867", u"荣昌": "2876", u"石柱": "2889", u"丰都": "2880", u"巫山": "2887", u"永川": "2870",
               u"江津": "2868", u"南岸": "2857"},
        'other': {u"南充": "51", u"漳州": "80", u"清远": "270", u"黄南": "189", u"莆田": "77", u"佛山": "20", u"大理": "237", u"石河子": "255", u"塔城": "253", u"鹰潭": "219", u"三亚": "144",
                  u"恩施": "331", u"德州": "308", u"鸡西": "95", u"宜宾": "52", u"安阳": "109", u"通辽": "149", u"宿迁": "292", u"黑河": "101", u"榆林": "183", u"茂名": "22", u"阿拉尔": "374",
                  u"厦门": "76", u"宿州": "130", u"阿坝": "283", u"黄冈": "328", u"文山": "233", u"海北": "188", u"揭阳": "272", u"伊春": "99", u"三门峡": "296", u"儋州": "378", u"柳州": "133",
                  u"东莞": "24", u"三明": "78", u"周口": "299", u"安庆": "127", u"德宏": "238", u"上饶": "224", u"安康": "184", u"玉溪": "227", u"武汉": "194", u"池州": "315", u"襄阳": "196",
                  u"开封": "293", u"内江": "277", u"阿拉善": "322", u"临沂": "307", u"淮南": "310", u"大庆": "98", u"定西": "175", u"临沧": "232", u"吐鲁番": "243", u"金昌": "167", u"六安": "132",
                  u"遵义": "38", u"泰安": "305", u"南通": "70", u"淮北": "311", u"凉山": "54", u"阜新": "287", u"松原": "90", u"景德镇": "215", u"贵阳": "36", u"贵港": "137", u"常州": "69",
                  u"吕梁": "323", u"五指山": "353", u"荆州": "198", u"扬州": "74", u"海口": "143", u"林芝": "262", u"四平": "86", u"攀枝花": "274", u"澳门": "345", u"赣州": "220", u"威海": "120",
                  u"荆门": "200", u"郫县": "381", u"乌鲁木齐": "241", u"玉林": "138", u"衡阳": "207", u"桂林": "134", u"义乌": "386", u"红河": "234", u"杭州": "26", u"临汾": "164", u"青岛": "114",
                  u"包头": "146", u"广元": "275", u"平顶山": "105", u"仙桃": "202", u"台州": "35", u"甘孜": "284", u"甘南": "326", u"龙岩": "82", u"庆阳": "174", u"保山": "228", u"即墨": "380",
                  u"中山": "25", u"新余": "218", u"牡丹江": "302", u"湖州": "30", u"图木舒克": "375", u"湘潭": "206", u"朝阳市": "289", u"漯河": "110", u"乐山": "50", u"淮安": "72", u"乌海": "147",
                  u"重庆": "15", u"香港": "344", u"焦作": "106", u"十堰": "197", u"石嘴山": "339", u"胶州": "379", u"合肥": "123", u"南宁": "142", u"孝感": "327", u"果洛": "191", u"成都": "45",
                  u"海西": "193", u"保定": "6", u"呼和浩特": "145", u"温州": "28", u"延安": "181", u"晋城": "159", u"邵阳": "208", u"鹤壁": "107", u"博尔塔拉": "251", u"承德": "8", u"日照": "306",
                  u"晋中": "161", u"怀化": "336", u"潮州": "271", u"昌吉": "250", u"常德": "210", u"许昌": "295", u"烟台": "118", u"福州": "75", u"抚顺": "58", u"济南": "113", u"广安": "278",
                  u"山南": "258", u"楚雄": "236", u"潜江": "203", u"石家庄": "1", u"张家界": "334", u"吉安": "221", u"肇庆": "265", u"信阳": "298", u"太原": "155", u"辽源": "87", u"齐齐哈尔": "94",
                  u"双鸭山": "97", u"苏州": "67", u"新乡": "108", u"永州": "212", u"衢州": "33", u"汕头": "19", u"聊城": "309", u"和田": "245", u"日喀则": "259", u"娄底": "213", u"黔西南": "42",
                  u"洛阳": "104", u"防城港": "318", u"咸宁": "329", u"盘锦": "63", u"葫芦岛": "64", u"钦州": "136", u"崇左": "320", u"江门": "21", u"酒泉": "173", u"南昌": "214", u"辽阳": "62",
                  u"衡水": "11", u"宣城": "316", u"梧州": "135", u"固原": "341", u"郴州": "211", u"镇江": "290", u"伊犁": "252", u"黔南": "44", u"本溪": "286", u"锦州": "60", u"随州": "330",
                  u"大兴安岭": "303", u"商丘": "297", u"绍兴": "31", u"六盘水": "37", u"济宁": "304", u"湘西": "337", u"绥化": "102", u"吴忠": "340", u"金华": "32", u"无锡": "66", u"雅安": "280",
                  u"亳州": "314", u"临夏": "325", u"邢台": "5", u"廊坊": "10", u"昆明": "225", u"深圳": "17", u"宁波": "27", u"邯郸": "4", u"黔东南": "43", u"运城": "162", u"黄石": "195", u"琼海": "377",
                  u"通化": "88", u"上海": "13", u"潍坊": "119", u"贺州": "319", u"普洱": "231", u"白城": "91", u"资阳": "282", u"曲靖": "226", u"长治": "158", u"兴安": "154", u"湛江": "264",
                  u"哈尔滨": "93", u"呼伦贝尔": "151", u"渭南": "180", u"鞍山": "57", u"长沙": "204", u"双流": "382", u"中卫": "342", u"泸州": "47", u"常熟": "384", u"陇南": "324", u"菏泽": "338",
                  u"德阳": "48", u"铜仁": "40", u"广州": "16", u"阜阳": "129", u"岳阳": "209", u"大连": "56", u"丹东": "59", u"萍乡": "216", u"兰州": "166", u"梅州": "266", u"嘉峪关": "343",
                  u"沈阳": "55", u"绵阳": "49", u"海东": "187", u"阿勒泰": "254", u"遂宁": "276", u"泉州": "79", u"河源": "268", u"营口": "61", u"莱芜": "121", u"那曲": "260", u"宜昌": "199",
                  u"七台河": "301", u"滁州": "128", u"朔州": "160", u"张家口": "7", u"铜陵": "312", u"怒江": "239", u"平凉": "172", u"益阳": "335", u"北海": "317", u"宜春": "222", u"天水": "169",
                  u"阳泉": "157", u"咸阳": "179", u"自贡": "46", u"云浮": "273", u"安顺": "39", u"丽江": "230", u"北京": "12", u"拉萨": "256", u"阿里": "261", u"西安": "176", u"宝鸡": "178",
                  u"西宁": "186", u"丽水": "285", u"喀什": "247", u"驻马店": "300", u"玉树": "192", u"铜川": "177", u"连云港": "71", u"来宾": "141", u"巴音郭楞": "249", u"昭通": "229", u"达州": "53",
                  u"五家渠": "376", u"濮阳": "294", u"芜湖": "124", u"汕尾": "267", u"阳江": "269", u"九江": "217", u"海南州": "190", u"抚州": "223", u"铁岭": "288", u"枣庄": "116", u"武威": "170",
                  u"鹤岗": "96", u"大同": "156", u"银川": "165", u"毕节": "41", u"株洲": "205", u"珠海": "18", u"库尔勒": "373", u"延边朝鲜族自治": "92", u"昆山": "383", u"西双版纳": "235", u"忻州": "163",
                  u"乌兰察布": "153", u"巴中": "281", u"张掖": "171", u"济源": "112", u"佳木斯": "100", u"泰州": "291", u"韶关": "263", u"淄博": "115", u"天津": "14", u"神农架": "333", u"鄂尔多斯": "150",
                  u"南平": "81", u"河池": "140", u"黄山": "313", u"唐山": "2", u"白山": "89", u"蚌埠": "125", u"商洛": "185", u"吉林": "85", u"鄂州": "201", u"滨州": "122", u"徐州": "68", u"阿克苏": "246",
                  u"慈溪": "385", u"巢湖": "131", u"东营": "117", u"南阳": "111", u"马鞍山": "126", u"巴彦淖尔": "152", u"惠州": "23", u"百色": "139", u"长春": "84", u"哈密": "244", u"克孜勒苏": "248",
                  u"眉山": "279", u"嘉兴": "29", u"克拉玛依": "242", u"汉中": "182", u"迪庆": "240", u"盐城": "73", u"白银": "168", u"锡林郭勒": "321", u"秦皇岛": "3", u"天门": "332", u"昌都": "257",
                  u"赤峰": "148", u"沧州": "9", u"南京": "65", u"舟山": "34", u"郑州": "103", u"宁德": "83"}
    }
    return address_keywords_dict[city][area]

def jobs(job):
    job_dict = {
        u"Helpdesk 技术支持": ["qzjishuzhichi", "qzjisuanjiwangluo"], u"产品/品牌专员": ["qzchanpinjingli", "qzjisuanjiwangluo"], u"数码直印/菲林输出": ["qzyinshuazhiban", "qzmeishusheji"],
        u"建筑工程师": ["qzgongchengshi", "qzjianzhuzhuangxiu"], u"钳工/机修工/钣金工": ["qzbanjingong", "qzjigongyibangongren"], u"嵌入式软件开发(Linux/单片机/PLC/DSP…)": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"],
        u"预结算员": ["qzzjyysy", "qzjianzhuzhuangxiu"], u"投诉专员": ["qzshouhoufuwu", "qzqiche"], u"网站架构设计师": ["qzxitongjiagoushi", "qzjisuanjiwangluo"], u"高级软件工程师": ["qzruanjiangongchengshi", "qzjisuanjiwangluo"],
        u"纸样师/车板工": ["qzyangyigong", "qzjigongyibangongren"], u"契约管理": ["qzqiyueguanli", "qzbaoxianjingjiren"], u"理货员": ["qzlihuoyuan", "qzbaihuolingshou"], u"财务/会计助理": ["qzkuaijizhuli", "qzcaiwushenji"],
        u"情报信息分析人员": ["qzshichangdiaoyan", "qzshichanggongguan"], u"家政服务/保姆": ["qzbaomu", "qzjiazhenganbao"], u"发型师": ["qzmeifashi", "qzmeirongmeifazhiwei"], u"数据通信工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"],
        u"金融产品经理": ["qzrongzijingli", "qzjinrongtouzizhengquan"], u"海关事务管理": ["qzwuliujingli", "qzmaoyiyunshu"], u"制造工程师": ["qzjixiegongchengshi", "qzjixieyiqiyibiao"], u"采购总监": ["qzcaigoujingli", "qzmaoyiyunshu"],
        u"预定部主管": ["qzydbzhuguan", "qzjiudiancanyin"], u"石油天然气技术人员": ["qzshiyoujishu", "qzdianqinengyuan"], u"语音/视频开发工程师": ["qzyuyinshipintuxing", "qzjisuanjiwangluo"], u"SEO搜索引擎优化": ["qzwangzhanyunying", "qzjisuanjiwangluo"],
        u"服装/纺织/皮革工艺师": ["qzfuzhuangzhuli", "qzmeitiyingshi"], u"德语翻译": ["qzdeyufanyi", "qzfanyi"], u"裁缝印纺熨烫": ["qzfengrengong", "qzjigongyibangongren"], u"理疗师": ["qzliliaoshi", "qzyiyuanyiliao"],
        u"生物工程/生物制药": ["qzshengwugongcheng", "qzyiyaoshengwu"], u"礼仪/迎宾": ["qzyingbin", "qzjiudiancanyin"], u"全科医生": ["qzneikeyisheng", "qzyiyuanyiliao"], u"品类经理": ["qzquyuqudao", "qzshichangyingxiao"], u"后勤": ["qzneiqin", "qzxingzhenghouqin"],
        u"电子/电器维修工程师/技师": ["qzdianqiweixiugong", "qzjigongyibangongren"], u"工业/产品设计": ["qzbaozhuangsheji", "qzmeishusheji"], u"人力资源伙伴(HRBP)": ["qzrenshizhuli", "qzrenliziyuan"], u"信贷管理": ["qzxindaiguanli", "qzjinrongtouzizhengquan"],
        u"宴会管理": ["qzhunlifuwu", "qzguanggaohuizhanzhiwei"], u"医疗器械研发": ["qzylqxtuiguang", "qzyiyaoshengwu"], u"审计经理/主管": ["qzshenjijingli", "qzcaiwushenji"], u"养殖部主管": ["qzyangzhirenyuan", "qznonglin"],
        u"给排水/暖通工程": ["qzjipaishui", "qzjianzhuzhuangxiu"], u"市场企划经理/主管": ["qzscchjingli", "qzshichanggongguan"], u"楼面经理": ["qzloumianjingli", "qzjiudiancanyin"], u"调酒师/侍酒师/吧台员": ["qztiaojiushi", "qzjiudiancanyin"],
        u"培训讲师": ["qzpeixunshi", "qzjiaoyupeixun"], u"二手车评估师": ["qzescpinggushi", "qzqiche"], u"审计专员/助理": ["qzshenjizhuanyuan", "qzcaiwushenji"], u"放映经理/主管": ["qzyingshicehua", "qzmeitiyingshi"],
        u"房地产评估": ["qzxindaiguanli", "qzjinrongtouzizhengquan"], u"意大利语翻译": ["qzfanyiqita", "qzfanyi"], u"建筑工程安全管理": ["qzjzgcguanli", "qzjianzhuzhuangxiu"], u"发型助理/学徒": ["qzmeifashi", "qzmeirongmeifazhiwei"],
        u"裁床": ["qzqiegejigong", "qzjigongyibangongren"], u"餐饮/娱乐管理": ["qzlingban", "qzjiudiancanyin"], u"空调工/电梯工/锅炉工": ["qzguolugong", "qzjigongyibangongren"], u"信息技术专员": ["qztxjsgongchengshi", "qzjisuanjiwangluo"],
        u"业务拓展主管/经理": ["qzyewutuozhan", "qzguanggaohuizhanzhiwei"], u"系统测试": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"网络推广经理/主管": ["qzwangluoxiaoshou", "qzshichangyingxiao"],
        u"ERP实施顾问": ["qzruanjianshishigongchengshi", "qzjisuanjiwangluo"], u"汽车底盘/总装工程师": ["qzzuzhuanggong", "qzjigongyibangongren"], u"EHS管理": ["qzehsguanli", "qzhuanjingbaohu"], u"体系工程师/审核员": ["qzzlgongchengshi", "qzjisuanjiwangluo"],
        u"生产总监": ["qzjishuzongjian", "qzjisuanjiwangluo"], u"销售助理": ["qzxiaoshouzhuli", "qzshichangyingxiao"], u"销售行政专员/助理": ["qzxiaoshouzhuli", "qzshichangyingxiao"], u"变压器与磁电工程师": ["qzcdgongchengshi", "qzdianqinengyuan"],
        u"高级客户经理/客户经理": ["qzdakehujingli", "qzshichangyingxiao"], u"建筑工程管理/项目经理": ["qzjzgcguanli", "qzjianzhuzhuangxiu"], u"咨询总监": ["qzzixunzongjian", "qzzixunguwen"], u"公关专员": ["qzgongguanjingli", "qzshichanggongguan"],
        u"寻呼员/话务员": ["qzqiantai", "qzxingzhenghouqin"], u"咨询项目管理": ["qzxiangmuguanli", "qzguanggaohuizhanzhiwei"], u"储备干部": ["qzchubeiganbu", "qzjiaoyupeixun"], u"首席执行官CEO/总裁/总经理": ["qzzonggongchengshi", "qzshengchanzhizaozhiwei"],
        u"金融/经济研究员": ["qztouziguwen", "qzjinrongtouzizhengquan"], u"销售主管": ["qzxiaoshoujingli", "qzshichangyingxiao"], u"涂料研发工程师": ["qzzsgongchengshi", "qzjixieyiqiyibiao"], u"光伏技术工程师": ["qzdligongchengshi", "qzdianqinengyuan"],
        u"网店店长/客服": ["qztaobaokefu", "qztaobao"], u"传菜主管/传菜员": ["qzchuancaiyuan", "qzjiudiancanyin"], u"包装工程师": ["qzbaozhuangjixie", "qzjixieyiqiyibiao"], u"列车设计与制造": ["qzfeixingqisheji", "qzjixieyiqiyibiao"],
        u"展览/展示/店面设计": ["qzzhanlansheji", "qzmeishusheji"], u"理科教师": ["qzjiaoshi", "qzjiaoyupeixun"], u"客房服务员/楼面服务员": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"营业部大堂经理": ["qzdatangjingli", "qzjiudiancanyin"],
        u"园艺/园林/景观设计": ["qzyuanyisheji", "qznonglin"], u"司机": ["qzhuoyunsiji", "qzsiji"], u"影视策划/制作人员": ["qzyingshicehua", "qzmeitiyingshi"], u"首席人力资源官CHO/HRVP": ["qzrenshizongjian", "qzrenliziyuan"],
        u"合规主管/专员": ["qzfalvguwen", "qzfalv"], u"策略发展总监": ["qzscchjingli", "qzshichanggongguan"], u"环境/健康/安全工程师（EHS）": ["qzehsguanli", "qzhuanjingbaohu"], u"高中教师": ["qzjiaoshi", "qzjiaoyupeixun"],
        u"汽车/摩托车工程师": ["qzqcgongchengshi", "qzjixieyiqiyibiao"], u"网络推广总监": ["qzwangluotuiguang", "qzjisuanjiwangluo"], u"西班牙语翻译": ["qzfanyiqita", "qzfanyi"], u"物流总监": ["qzwuliuzhuanyuan", "qzmaoyiyunshu"],
        u"财务主管/总帐主管": ["qzcaiwuzhuguan", "qzcaiwushenji"], u"列车/地铁车长": ["qzluhaikongyun", "qzmaoyiyunshu"], u"客户主管/专员": ["qzkehuzhuguan", "qzguanggaohuizhanzhiwei"], u"产品/品牌主管": ["qzchanpinjingli", "qzjisuanjiwangluo"],
        u"外语培训师": ["qzyingyufanyi", "qzfanyi"], u"仓库管理员": ["qzcangkuguanli", "qzmaoyiyunshu"], u"输电线路工程师": ["qzdligongchengshi", "qzdianqinengyuan"], u"兽医": ["qzshouyishouyi", "qzyiyuanyiliao"],
        u"环境影响评价工程师": ["qzytgongchengshi", "qzjianzhuzhuangxiu"], u"招投标管理": ["qzfdcxmzhuanyuan", "qzfangjingjiren"], u"房地产中介/交易": ["qzwuyezushou", "qzwuye"], u"船舶工程师": ["qzcbgongchengshi", "qzjixieyiqiyibiao"],
        u"技术文员/助理": ["qzwenmiwenyuan", "qzxingzhenghouqin"], u"美术指导": ["qzmeishuzhidao", "qzguanggaohuizhanzhiwei"], u"空调/热能工程师": ["qzktgongchengshi", "qzdianqinengyuan"], u"科研人员": ["qzkeyanrenyuan", "qzjiaoyupeixun"],
        u"餐饮/娱乐服务员": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"薪资福利经理/主管": ["qzxzfljingli", "qzrenliziyuan"], u"猎头/人才中介": ["qzlietouguwen", "qzrenliziyuan"], u"幼教": ["qzyoujiao", "qzjiaoyupeixun"],
        u"总裁助理/总经理助理": ["qzwenmiwenyuan", "qzxingzhenghouqin"], u"生产主管/督导/领班/组长": ["qzshengchanzhuguan", "qzshengchanzhizaozhiwei"], u"音效师": ["qzpeiyin", "qzmeitiyingshi"], u"兼职": ["qzshixisheng", "qzjiaoyupeixun"],
        u"游戏策划师": ["qzyouxisheji", "qzjisuanjiwangluo"], u"高级硬件工程师": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"], u"市场企划专员": ["qzscchjingli", "qzshichanggongguan"], u"报关与报检": ["qzbaoguanyuan", "qzmaoyiyunshu"],
        u"可靠度工程师": ["qzzlgongchengshi", "qzjisuanjiwangluo"], u"资产评估/分析": ["qzxindaiguanli", "qzjinrongtouzizhengquan"], u"售前/售后技术支持工程师": ["qzshzcgongchengshi", "qzkefu"], u"媒介销售": ["qzgongguanjingli", "qzshichanggongguan"],
        u"功能测试": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"售后服务/客户服务": ["qzshouhoufuwu", "qzqiche"], u"首席财务官 CFO": ["qzcaiwuzongjian", "qzcaiwushenji"], u"导游/旅行顾问": ["qzdaoyou", "qzlvyouzhiwei"],
        u"制作执行": ["qzzhizuozhixing", "qzguanggaohuizhanzhiwei"], u"汽车定损/车险理赔": ["qzbaoxianlipei", "qzbaoxianjingjiren"], u"资料员": ["qzcailiaoyuan", "qzjianzhuzhuangxiu"], u"医疗技术人员": ["qzkeyanrenyuan", "qzjiaoyupeixun"],
        u"系统集成工程师": ["qzxitonggongchengshi", "qzjisuanjiwangluo"], u"医疗器械维修人员": ["qzylqxtuiguang", "qzyiyaoshengwu"], u"印刷排版/制版": ["qzyinshuazhiban", "qzmeishusheji"], u"市场分析/调研人员": ["qzshichangdiaoyan", "qzshichanggongguan"],
        u"音乐/美术教师": ["qzjiaoshi", "qzjiaoyupeixun"], u"软件测试": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"网页设计/制作/美工": ["qzwangyesheji", "qzjisuanjiwangluo"], u"网站营运总监": ["qzwangzhanyunying", "qzjisuanjiwangluo"],
        u"医药招商": ["qzyiyaodaibiao", "qzshichangyingxiao"], u"水利/水电工程师": ["qzshuidiangongchengshi", "qzdianqinengyuan"], u"经纪业务": ["qzfdcjingjiren", "qzfangjingjiren"], u"销售经理": ["qzxiaoshoujingli", "qzshichangyingxiao"],
        u"施工员": ["qzshigongyuan", "qzjianzhuzhuangxiu"], u"导购员": ["qzdaogou", "qzbaihuolingshou"], u"有线传输工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"], u"信审核查": ["qzshenjizhuanyuan", "qzcaiwushenji"], u"快递员": ["qzkuaidi", "qzmaoyiyunshu"],
        u"产品总监": ["qzchanpinjingli", "qzjisuanjiwangluo"], u"电子商务经理/主管": ["qzyewuzhichi", "qztaobao"], u"贸易/外贸经理/主管": ["qzgnmyjingli", "qzmaoyiyunshu"], u"医药销售代表": ["qzyiyaodaibiao", "qzshichangyingxiao"],
        u"性能测试": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"物业维修人员": ["qzwuyeweixiu", "qzwuye"], u"技术支持/维护工程师": ["qzjishuzhichi", "qzjisuanjiwangluo"], u"测试工程师": ["qzceshigongchengshi", "qzjisuanjiwangluo"],
        u"面料辅料开发": ["qzyangyigong", "qzjigongyibangongren"], u"开发报建专员": ["qzfdcxmzhuanyuan", "qzfangjingjiren"], u"网站维护工程师": ["qzjishuzhichi", "qzjisuanjiwangluo"], u"法语翻译": ["qzfayufanyi", "qzfanyi"],
        u"投资者关系": ["qzzichanguanli", "qzcaiwushenji"], u"理财顾问/财务规划师": ["qztouziguwen", "qzjinrongtouzizhengquan"], u"工程/设备经理": ["qzsbgongchengshi", "qzjianzhuzhuangxiu"], u"技术支持/维护经理": ["qzjishuzhichi", "qzjisuanjiwangluo"],
        u"印刷机械机长": ["qzbaozhuangjixie", "qzjixieyiqiyibiao"], u"采购助理": ["qzcaigoujingli", "qzmaoyiyunshu"], u"美容助理/见席美容师": ["qzmeirongshi", "qzmeirongmeifazhiwei"], u"首席技术执行官CTO/首席信息官CIO": ["qzzonggongchengshi", "qzshengchanzhizaozhiwei"],
        u"视觉设计师": ["qzpingmiansheji", "qzmeishusheji"], u"家用电器/数码产品研发": ["qzdianqiweixiugong", "qzjigongyibangongren"], u"生产设备管理": ["qzshebeiweihu", "qzshengchanzhizaozhiwei"], u"化妆品研发": ["qzyiyaodaibiao", "qzshichangyingxiao"],
        u"会务/会展专员": ["qzhuiwujingli", "qzshichanggongguan"], u"咨询热线/呼叫中心服务人员": ["qzhujiaozhongxin", "qzkefu"], u"艺术/设计总监": ["qzpingmiansheji", "qzmeishusheji"], u"出版/发行": ["qzchuban", "qzbianjichuban"],
        u"化学分析测试员": ["qzjianyanjiance", "qzqiche"], u"贸易/外贸专员/助理": ["qzwaimaozhuanyuan", "qzmaoyiyunshu"], u"土建造价工程师": ["qzzjyysy", "qzjianzhuzhuangxiu"], u"汽车质量管理": ["qzzlgongchengshi", "qzjisuanjiwangluo"],
        u"熟食加工": ["qzshipinchuli", "qzbaihuolingshou"], u"铸造/锻造工程师/技师": ["qzzzgongchengshi", "qzjixieyiqiyibiao"], u"半导体技术": ["qzjmjxgongchengshi", "qzjixieyiqiyibiao"], u"大堂经理": ["qzdatangjingli", "qzjiudiancanyin"],
        u"临床研究员": ["qzwaikeyisheng", "qzyiyuanyiliao"], u"工艺工程师": ["qzgongyisheji", "qzshengchanzhizaozhiwei"], u"规划设计总监": ["qzchengshisheji", "qzjianzhuzhuangxiu"], u"牙科医生": ["qzyakeyisheng", "qzyiyuanyiliao"],
        u"公关/媒介助理": ["qzgongguanjingli", "qzshichanggongguan"], u"空乘人员": ["qzluhaikongyun", "qzmaoyiyunshu"], u"企业/业务发展经理": ["qzqiyecehua", "qzguanggaohuizhanzhiwei"], u"项目管理": ["qzxiangmuguanli", "qzguanggaohuizhanzhiwei"],
        u"钢结构工程师": ["qztjgongchengshi", "qzjianzhuzhuangxiu"], u"清洁工": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"茶艺师": ["qzchayishi", "qzjiudiancanyin"], u"环境/健康/安全经理/主管（EHS）": ["qzehsguanli", "qzhuanjingbaohu"],
        u"专业培训师": ["qzpeixunshi", "qzjiaoyupeixun"], u"销售工程师": ["qzxiaoshoudaibiao", "qzshichangyingxiao"], u"安全员": ["qzshigongyuan", "qzjianzhuzhuangxiu"], u"Flash设计/开发": ["qzwangyesheji", "qzjisuanjiwangluo"],
        u"公共卫生/疾病控制": ["qzjibingkongzhi", "qzyiyuanyiliao"], u"锅炉工程师/技师": ["qzglgongchengshi", "qzjixieyiqiyibiao"], u"客服专员/助理(非技术)": ["qzkefuzhuli", "qzkefu"], u"运维工程师": ["qzjishuzhichi", "qzjisuanjiwangluo"],
        u"外语教师": ["qzyingyufanyi", "qzfanyi"], u"数据库工程师/管理员": ["qzshujukuguanli", "qzjisuanjiwangluo"], u"测绘/测量": ["qzclychy", "qzjianzhuzhuangxiu"], u"咨询经理": ["qzzixunjingli", "qzzixunguwen"],
        u"美容整形师": ["qzmeirongzhengxingshi", "qzyiyuanyiliao"], u"美甲师": ["qzmeijiashi", "qzmeirongmeifazhiwei"], u"技术总监/经理": ["qzjishuzongjian", "qzjisuanjiwangluo"], u"增值产品开发工程师": ["qzjishuzhichi", "qzjisuanjiwangluo"],
        u"酒店/宾馆营销": ["qzbkfwjingli", "qzjiudiancanyin"], u"智能大厦/综合布线/安防/弱电": ["qzzonghebuxian", "qzdianqinengyuan"], u"临床数据分析员": ["qzlinchuangyanjiu", "qzyiyaoshengwu"], u"项目工程师": ["qzxiangmuzhuguanjingli", "qzyiyaoshengwu"],
        u"投资银行业务": ["qzyinhangjingli", "qzjinrongtouzizhengquan"], u"税务经理/税务主管": ["qzshuiwujingli", "qzcaiwushenji"], u"校长": ["qzjiaoxueguanlirenyuan", "qzjiaoyupeixun"], u"收银主管/收银员": ["qzshouyinyuan", "qzbaihuolingshou"],
        u"安防主管": ["qzxiaofangzhongkong", "qzbaihuolingshou"], u"技工": ["qzjggrqita", "qzjigongyibangongren"], u"财务顾问": ["qzcaiwujingli", "qzcaiwushenji"], u"团购业务员": ["qztuangouyewuyuan", "qzshichangyingxiao"],
        u"培训助理": ["qzpeixunzhuanyuan", "qzrenliziyuan"], u"资金经理/主管": ["qzchengbenjingli", "qzcaiwushenji"], u"活动策划": ["qzwenan", "qzguanggaohuizhanzhiwei"], u"宠物护理/美容": ["qzchongwumeirongshi", "qzmeirongmeifazhiwei"],
        u"绩效考核专员/助理": ["qzjxkhzhuli", "qzrenliziyuan"], u"电子工程师/技术员": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"], u"供应链总监": ["qzgnmyjingli", "qzmaoyiyunshu"], u"房地产项目管理": ["qzfdccehua", "qzfangjingjiren"],
        u"出纳员": ["qzchuna", "qzcaiwushenji"], u"电焊工/铆焊工": ["qzbanjingong", "qzjigongyibangongren"], u"网站编辑": ["qzwangzhanbianji", "qzjisuanjiwangluo"], u"健身房服务": ["qzjianshenjiaolian", "qzyundongjianshenzhiwei"],
        u"成本经理": ["qzchengbenjingli", "qzcaiwushenji"], u"预定员": ["qzjdyudingyuan", "qzjiudiancanyin"], u"动物营养/饲料研发": ["qzsiliaoyewu", "qznonglin"], u"按摩/足疗": ["qzanmoshi", "qzbaojiananmo"], u"单证员": ["qzbaoguanyuan", "qzmaoyiyunshu"],
        u"行政专员/助理": ["qzxingzhengzhuli", "qzxingzhenghouqin"], u"UI设计师/顾问": ["qzwangyesheji", "qzjisuanjiwangluo"], u"业务跟单": ["qzgendanyuan", "qzmaoyiyunshu"], u"团购经理/主管": ["qztuangouyewuyuan", "qzshichangyingxiao"],
        u"电脑操作员/打字员": ["qzcaozuogong", "qzjigongyibangongren"], u"网站策划": ["qzxuqiufenxishi", "qzjisuanjiwangluo"], u"冶金工程师": ["qzhuagongjishu", "qzshengchanzhizaozhiwei"], u"业务跟单经理": ["qzgendanyuan", "qzmaoyiyunshu"],
        u"手机应用开发工程师": ["qzruanjiangongchengshi", "qzjisuanjiwangluo"], u"产品管理": ["qzchanpinjingli", "qzjisuanjiwangluo"], u"电池/电源开发": ["qzdlugongchengshi", "qzdianqinengyuan"], u"电工": ["qzdiangong", "qzjigongyibangongren"],
        u"晒版/拼版/装订/烫金技工": ["qzzhuangding", "qzbianjichuban"], u"生鲜食品加工/处理": ["qzshipinchuli", "qzbaihuolingshou"], u"塑料工程师": ["qzzsgongchengshi", "qzjixieyiqiyibiao"], u"会务/会展经理": ["qzhuiwujingli", "qzshichanggongguan"],
        u"行程管理/计调": ["qzjidiao", "qzlvyouzhiwei"], u"理货员/陈列员/收货员": ["qzlihuoyuan", "qzbaihuolingshou"], u"资金专员": ["qzzichanguanli", "qzcaiwushenji"], u"网络工程师": ["qzwangluoguanliyuan", "qzjisuanjiwangluo"],
        u"调度员": ["qzdiaoduyuan", "qzmaoyiyunshu"], u"培训产品开发": ["qzjycpkaifa", "qzjiaoyupeixun"], u"售前/售后技术支持经理": ["qzshzcjingli", "qzkefu"], u"美术编辑": ["qzmeishubianji", "qzmeishusheji"], u"护理主任/护士长": ["qzhushichang", "qzyiyuanyiliao"],
        u"保险理赔": ["qzbaoxianlipei", "qzbaoxianjingjiren"], u"法务主管/专员": ["qzfawurenyuan", "qzfalv"], u"汽车电子工程师": ["qzjmjxgongchengshi", "qzjixieyiqiyibiao"], u"讲师/助教": ["qzzhujiao", "qzjiaoyupeixun"],
        u"电分操作员": ["qzyinshuazhiban", "qzmeishusheji"], u"测试经理": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"司仪": ["qzzhuchi", "qzjiudiancanyin"], u"校对/录入": ["qzjiaoduiluru", "qzbianjichuban"], u"保镖": ["qzbaoan", "qzjiazhenganbao"],
        u"大学/大专应届毕业生": ["qzbiyesheng", "qzjiaoyupeixun"], u"农艺师": ["qznysnongyishi", "qznonglin"], u"网站营运经理/主管": ["qzwangzhanyunying", "qzjisuanjiwangluo"], u"冲压工程师/技师": ["qzcygongchengshi", "qzjixieyiqiyibiao"],
        u"电子技术研发工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"], u"厨师助理/学徒": ["qzshitangchushi", "qzjiudiancanyin"], u"物业设施管理人员": ["qzwyssguanli", "qzwuye"], u"专科医生": ["qzzhuankeyisheng", "qzyiyuanyiliao"],
        u"高级物业顾问/物业顾问": ["qzwuyeguwen", "qzwuye"], u"合同管理": ["qzfengxianguanli", "qzjinrongtouzizhengquan"], u"彩妆培训师": ["qzmeirongzhengxingshi", "qzyiyuanyiliao"], u"首席运营官COO": ["qzshichangzongjian", "qzshichanggongguan"],
        u"兼职教师": ["qzjiaoshi", "qzjiaoyupeixun"], u"阿拉伯语翻译": ["qzfanyiqita", "qzfanyi"], u"化验员": ["qzhuayanjianyan", "qzshengchanzhizaozhiwei"], u"统计员": ["qztongji", "qzcaiwushenji"], u"船员": ["qzluhaikongyun", "qzmaoyiyunshu"],
        u"实习生": ["qzshixisheng", "qzjiaoyupeixun"], u"多媒体/游戏开发工程师": ["qzyouxisheji", "qzjisuanjiwangluo"], u"自动化测试": ["qzzidongkongzhi", "qzdianqinengyuan"], u"业务分析经理/主管": ["qzshichangdiaoyan", "qzshichanggongguan"],
        u"市政工程师": ["qzhangdaogongcheng", "qzjianzhuzhuangxiu"], u"运输经理/主管": ["qzwuliujingli", "qzmaoyiyunshu"], u"客服主管(非技术)": ["qzkefuzongjian", "qzkefu"], u"运维经理": ["qzjishuzhichi", "qzjisuanjiwangluo"],
        u"院校教务管理人员": ["qzjiaoxueguanlirenyuan", "qzjiaoyupeixun"], u"建筑制图/模型/渲染": ["qzjianzhusheji", "qzjianzhuzhuangxiu"], u"零配件销售": ["qzlpjxiaoshou", "qzqiche"], u"岩土工程": ["qzytgongchengshi", "qzjianzhuzhuangxiu"],
        u"工程/机械绘图员": ["qzjixiezhitu", "qzjixieyiqiyibiao"], u"客户关系经理/主管": ["qzkhgxguanli", "qzkefu"], u"平面设计经理/主管": ["qzpingmiansheji", "qzmeishusheji"], u"精密机械": ["qzjixiegongchengshi", "qzjixieyiqiyibiao"],
        u"物流主管": ["qzshichangjingli", "qzshichanggongguan"], u"企业文化/员工关系/工会管理": ["qzkhgxguanli", "qzkefu"], u"采购主管": ["qzcaigoujingli", "qzmaoyiyunshu"], u"食品/饮料研发": ["qzshengwugongcheng", "qzyiyaoshengwu"],
        u"财务总监": ["qzcaiwuzongjian", "qzcaiwushenji"], u"自动控制工程师/技术员": ["qzzidongkongzhi", "qzdianqinengyuan"], u"服装/纺织设计": ["qzfangzhigong", "qzjigongyibangongren"], u"音效设计师": ["qzpeiyin", "qzmeitiyingshi"],
        u"打样/制版": ["qzyinshuazhiban", "qzmeishusheji"], u"综合业务专员": ["qzhujiaozhongxin", "qzkefu"], u"需求工程师": ["qzxuqiufenxishi", "qzjisuanjiwangluo"], u"汽车动力系统工程师": ["qzqcgongchengshi", "qzjixieyiqiyibiao"],
        u"产品专员": ["qzchanpinjingli", "qzjisuanjiwangluo"], u"车工/磨工/铣工/冲压工/锣工": ["qzxigong", "qzjigongyibangongren"], u"放映员": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"楼宇自动化": ["qzzonghebuxian", "qzdianqinengyuan"],
        u"采购员": ["qzcaigou", "qzbaihuolingshou"], u"供应商开发": ["qzquyuqudao", "qzshichangyingxiao"], u"汽车安全性能工程师": ["qzjianyanjiance", "qzqiche"], u"研究生": ["qzbiyesheng", "qzjiaoyupeixun"], u"供应链主管/专员": ["qzwuliuzhuanyuan", "qzmaoyiyunshu"],
        u"公路桥梁预算师": ["qzglqlyusuanshi", "qzjianzhuzhuangxiu"], u"英语翻译": ["qzyingyufanyi", "qzfanyi"], u"总编/副总编": ["qzzhubian", "qzbianjichuban"], u"心理医生": ["qzxinliyisheng", "qzyiyuanyiliao"], u"财务分析经理/主管": ["qzcwfxjingli", "qzcaiwushenji"],
        u"固定资产会计": ["qzcaikuai", "qzcaiwushenji"], u"货运代理": ["qzhuoyunsiji", "qzsiji"], u"幕墙工程师": ["qzmqgongchengshi", "qzjianzhuzhuangxiu"], u"玩具设计": ["qzzhubaosheji", "qzmeishusheji"], u"大学教授": ["qzjiaoshi", "qzjiaoyupeixun"],
        u"医疗器械市场推广": ["qzylqxtuiguang", "qzyiyaoshengwu"], u"总监/部门经理": ["qzxingzhengzhuguan", "qzxingzhenghouqin"], u"绘画": ["qzsheyingzhuli", "qzmeitiyingshi"], u"普工/操作工": ["qzcaozuogong", "qzjigongyibangongren"],
        u"行业研究": ["qzshichangdiaoyan", "qzshichanggongguan"], u"结构/土木/土建工程师": ["qztjgongchengshi", "qzjianzhuzhuangxiu"], u"飞行器设计与制造": ["qzfeixingqisheji", "qzjixieyiqiyibiao"], u"市场/营销/拓展总监": ["qzscyxjingli", "qzshichanggongguan"],
        u"美容导师": ["qzmeirongdaoshi", "qzmeirongmeifazhiwei"], u"ERP技术开发": ["qzruanjianshishigongchengshi", "qzjisuanjiwangluo"], u"高级业务跟单": ["qzgendanyuan", "qzmaoyiyunshu"], u"气动工程师": ["qzdqgongchengshi", "qzdianqinengyuan"],
        u"运营经理": ["qzpinpaijingli", "qzshichanggongguan"], u"船务/空运陆运操作": ["qzluhaikongyun", "qzmaoyiyunshu"], u"高级建筑工程师/总工": ["qzzonggongchengshi", "qzshengchanzhizaozhiwei"], u"成本管理员": ["qzcbguanliyuan", "qzcaiwushenji"],
        u"标准化工程师": ["qzzlgongchengshi", "qzjisuanjiwangluo"], u"成本总监": ["qzchengbenjingli", "qzcaiwushenji"], u"房地产销售人员": ["qzfdcxiaoshou", "qzfangjingjiren"], u"轨道交通工程师/技术员": ["qzhangdaogongcheng", "qzjianzhuzhuangxiu"],
        u"房地产销售经理/主管": ["qzfdcxiaoshou", "qzfangjingjiren"], u"保险培训师": ["qzbaoxianpeixunshi", "qzbaoxianjingjiren"], u"餐饮/娱乐领班/部长": ["qzlingban", "qzjiudiancanyin"], u"副总经理/副总裁": ["qzxiaoshouzongjian", "qzshichangyingxiao"],
        u"保险产品开发/项目策划": ["qzbxchanpinkaifa", "qzbaoxianjingjiren"], u"证券/期货/外汇经纪人": ["qzqihuojingjiren", "qzjinrongtouzizhengquan"], u"无线通信工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"],
        u"成本经理/成本主管": ["qzchengbenjingli", "qzcaiwushenji"], u"软装设计师": ["qzshineisheji", "qzjianzhuzhuangxiu"], u"开发报建经理": ["qzfdcxmzhuanyuan", "qzfangjingjiren"], u"认证工程师/审核员": ["qzchanpinyanfa", "qzyiyaoshengwu"],
        u"原画师": ["qzsheyingshi", "qzmeitiyingshi"], u"物业管理经理/主管": ["qzwuyeguanlizhiwei", "qzwuye"], u"买手": ["qzwaimaozhuanyuan", "qzmaoyiyunshu"], u"化工技术应用/化工工程师": ["qzhuagongjishu", "qzshengchanzhizaozhiwei"],
        u"零售客户服务": ["qzshouhoufuwu", "qzqiche"], u"广告客户总监/副总监": ["qzkehuzongjian", "qzguanggaohuizhanzhiwei"], u"电子商务专员": ["qztaobaokefu", "qztaobao"], u"前厅接待": ["qzdatangjingli", "qzjiudiancanyin"],
        u"业务分析专员/助理": ["qzshichangjingli", "qzshichanggongguan"], u"文档工程师": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"装配工程师/技师": ["qzzuzhuanggong", "qzjigongyibangongren"], u"维修经理/主管": ["qzshebeiweixiu", "qzjixieyiqiyibiao"],
        u"企业秘书/董事会秘书": ["qzwenmiwenyuan", "qzxingzhenghouqin"], u"市场助理": ["qzshichangjingli", "qzshichanggongguan"], u"基金管理": ["qzjijinjinli", "qzjinrongtouzizhengquan"], u"打稿机操作员": ["qzyinshuazhiban", "qzmeishusheji"],
        u"模具工": ["qzmojugong", "qzjigongyibangongren"], u"保险内勤": ["qzbxneiqin", "qzbaoxianjingjiren"], u"特效设计师": ["qzhouqizhizuo", "qzmeitiyingshi"], u"规划与设计": ["qzchengshisheji", "qzjianzhuzhuangxiu"], u"后期制作": ["qzhouqizhizuo", "qzmeitiyingshi"],
        u"中医科医生": ["qzzykyisheng", "qzyiyuanyiliao"], u"爆破工程师": ["qzhangdaogongcheng", "qzjianzhuzhuangxiu"], u"物业管理专员/助理": ["qzwuyeguanlizhiwei", "qzwuye"], u"室内设计": ["qzshineisheji", "qzjianzhuzhuangxiu"],
        u"配色技术员": ["qzyinshuazhiban", "qzmeishusheji"], u"物料主管/专员": ["qzcaigoujingli", "qzmaoyiyunshu"], u"店长/卖场经理/楼面管理": ["qzdianzhang", "qzbaihuolingshou"], u"俄语翻译": ["qzeyufanyi", "qzfanyi"],
        u"工程监理": ["qzgongchengjianli", "qzjianzhuzhuangxiu"], u"保险核保": ["qzbaoxianlipei", "qzbaoxianjingjiren"], u"水处理工程师": ["qzwsclgongchengshi", "qzhuanjingbaohu"], u"化妆师/造型师": ["qzhuazhuangshi", "qzmeitiyingshi"],
        u"汽车机构工程师": ["qzqichexiaoshou", "qzshichangyingxiao"], u"生产计划/物料管理(PMC)": ["qzjihuadiaodu", "qzshengchanzhizaozhiwei"], u"科研管理人员": ["qzkeyanguanli", "qzjiaoyupeixun"], u"注塑工程师/技师": ["qzzsgongchengshi", "qzjixieyiqiyibiao"],
        u"编辑": ["qzwangzhanbianji", "qzjisuanjiwangluo"], u"融资总监": ["qzrongzijingli", "qzjinrongtouzizhengquan"], u"资产/资产管理": ["qzzichanguanli", "qzcaiwushenji"], u"汽车销售/经纪人": ["qzqichexiaoshou", "qzshichangyingxiao"],
        u"保险代理/经纪人/客户经理": ["qzbxjingjiren", "qzbaoxianjingjiren"], u"射频工程师": ["qzdlugongchengshi", "qzdianqinengyuan"], u"救生员": ["qzjiushengyuan", "qzyundongjianshenzhiwei"], u"涉外咨询师": ["qzshewaizixunshi", "qzzixunguwen"],
        u"电路工程师/技术员(模拟/数字)": ["qzdlugongchengshi", "qzdianqinengyuan"], u"水工/木工/漆工": ["qzmugong", "qzjigongyibangongren"], u"家具/家居用品设计": ["qzjiajusheji", "qzmeishusheji"], u"文案/策划": ["qzwenan", "qzguanggaohuizhanzhiwei"],
        u"机械工程师": ["qzjixiegongchengshi", "qzjixieyiqiyibiao"], u"药品市场推广主管/专员": ["qzyiyaodaibiao", "qzshichangyingxiao"], u"律师助理": ["qzlvshizhuli", "qzfalv"], u"计量工程师": ["qzjianyanjiance", "qzqiche"],
        u"采购经理": ["qzcaigoujingli", "qzmaoyiyunshu"], u"内科医生": ["qzneikeyisheng", "qzyiyuanyiliao"], u"物料经理": ["qzcaigoujingli", "qzmaoyiyunshu"], u"公司业务部门经理/主管": ["qzxiaoshoujingli", "qzshichangyingxiao"],
        u"防损员/内保": ["qzfangsunyuan", "qzbaihuolingshou"], u"质量管理/测试经理(QA/QC经理)": ["qzzhiliangguanli", "qzshengchanzhizaozhiwei"], u"职业技术教师": ["qzjiaoshi", "qzjiaoyupeixun"], u"水利/港口工程技术": ["qzshuidiangongchengshi", "qzdianqinengyuan"],
        u"项目经理/主管": ["qzxiangmuzhuguanjingli", "qzyiyaoshengwu"], u"培训专员/助理/培训师": ["qzpeixunzhuanyuan", "qzrenliziyuan"], u"医疗器械销售代表": ["qzylqxtuiguang", "qzyiyaoshengwu"], u"培训生": ["qzpeixunsheng", "qzjiaoyupeixun"],
        u"经纪人/星探": ["qzyingshicehua", "qzmeitiyingshi"], u"项目经理": ["qzxiangmujingli", "qzjisuanjiwangluo"], u"产品规划工程师": ["qzchengshisheji", "qzjianzhuzhuangxiu"], u"地勤人员": ["qzanjianyuan", "qzmaoyiyunshu"],
        u"会计": ["qzyinhangguiyuan", "qzjinrongtouzizhengquan"], u"酒店/宾馆经理": ["qzloumianjingli", "qzjiudiancanyin"], u"专业顾问": ["qzqiguanguwen", "qzzixunguwen"], u"包装设计": ["qzbaozhuangsheji", "qzmeishusheji"],
        u"厨师/面点师": ["qzmiandianshi", "qzjiudiancanyin"], u"中专/职校生": ["qzbiyesheng", "qzjiaoyupeixun"], u"市场通路专员": ["qzcuxiaojingli", "qzshichanggongguan"], u"渠道/分销总监": ["qzquyuqudao", "qzshichangyingxiao"],
        u"信息技术经理/主管": ["qztxjsgongchengshi", "qzjisuanjiwangluo"], u"公司业务客户经理": ["qzxiaoshoudaibiao", "qzshichangyingxiao"], u"工程造价师/预结算经理": ["qzzjyysy", "qzjianzhuzhuangxiu"], u"税务专员/助理": ["qzshuiwuzhuli", "qzcaiwushenji"],
        u"知识产权/专利/商标": ["qzzhuanliguwen", "qzfalv"], u"工程/设备工程师": ["qzsbgongchengshi", "qzjianzhuzhuangxiu"], u"仓库经理/主管": ["qzcangkuguanli", "qzmaoyiyunshu"], u"导演/编导": ["qzbiandao", "qzmeitiyingshi"],
        u"项目总监": ["qzxiangmuzhuguanjingli", "qzyiyaoshengwu"], u"电声/音响工程师/技术员": ["qzdengguangzhuli", "qzmeitiyingshi"], u"市场/营销/拓展主管": ["qzscyxjingli", "qzshichanggongguan"], u"营运经理": ["qzwangzhanyunying", "qzjisuanjiwangluo"],
        u"面料辅料采购": ["qzjihuadiaodu", "qzshengchanzhizaozhiwei"], u"医药销售经理/主管": ["qzyiyaodaibiao", "qzshichangyingxiao"], u"项目执行/协调人员": ["qzxiangmujingli", "qzjisuanjiwangluo"], u"行长/副行长": ["qzyinhangjingli", "qzjinrongtouzizhengquan"],
        u"焊接工程师/技师": ["qzhjgongchengshi", "qzjixieyiqiyibiao"], u"质量检验员/测试员": ["qzjianyanjiance", "qzqiche"], u"4S店经理/维修站经理": ["qz4sdguanli", "qzqiche"], u"供应商管理": ["qzypscguanli", "qzyiyaoshengwu"],
        u"会务/会展主管": ["qzhuiwujingli", "qzshichanggongguan"], u"行政经理/主管/办公室主任": ["qzxingzhengzhuguan", "qzxingzhenghouqin"], u"软件工程师": ["qzruanjiangongchengshi", "qzjisuanjiwangluo"], u"系统分析员": ["qzxitongjiagoushi", "qzjisuanjiwangluo"],
        u"营养师": ["qzyysyingyangshi", "qzyiyuanyiliao"], u"家教": ["qzjiajiaojiajiao", "qzjiaoyupeixun"], u"法务经理": ["qzfawurenyuan", "qzfalv"], u"政府事务管理": ["qzwuyeguanlizhiwei", "qzwuye"], u"造纸研发": ["qzhuagongjishu", "qzshengchanzhizaozhiwei"],
        u"脚本开发工程师": ["qzruanjiangongchengshi", "qzjisuanjiwangluo"], u"医疗器械生产/质量管理": ["qzylqxtuiguang", "qzyiyaoshengwu"], u"电气工程师/技术员": ["qzdqgongchengshi", "qzdianqinengyuan"], u"人事主管": ["qzrenshizhuguan", "qzrenliziyuan"],
        u"饲养员": ["qzyangzhirenyuan", "qznonglin"], u"渠道/分销经理": ["qzquyuqudao", "qzshichangyingxiao"], u"运维总监": ["qzjishuzhichi", "qzjisuanjiwangluo"], u"人事经理": ["qzrenshizhuguan", "qzrenliziyuan"],
        u"游戏界面设计师": ["qzyouxisheji", "qzjisuanjiwangluo"], u"品质经理": ["qzpinpaijingli", "qzshichanggongguan"], u"外科医生": ["qzwaikeyisheng", "qzyiyuanyiliao"], u"机场代表": ["qzluhaikongyun", "qzmaoyiyunshu"],
        u"客服总监(非技术)": ["qzkefuzongjian", "qzkefu"], u"集装箱业务": ["qzwuliuzhuanyuan", "qzmaoyiyunshu"], u"规划设计经理": ["qzchengshisheji", "qzjianzhuzhuangxiu"], u"医疗器械销售经理/主管": ["qzylqxtuiguang", "qzyiyaoshengwu"],
        u"维修工程师": ["qzjixieweixiugong", "qzjixieyiqiyibiao"], u"公关主管": ["qzgongguanjingli", "qzshichanggongguan"], u"电信交换工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"], u"会计文员": ["qzcaikuai", "qzcaiwushenji"],
        u"机电工程师": ["qzjdgongchengshi", "qzjixieyiqiyibiao"], u"护士/护理人员": ["qzhushi", "qzyiyuanyiliao"], u"计算机辅助设计工程师": ["qzjisuanjiqita", "qzjisuanjiwangluo"], u"网络推广专员": ["qzwangluotuiguang", "qzjisuanjiwangluo"],
        u"市场/营销/拓展专员": ["qzscyxjingli", "qzshichanggongguan"], u"仿真应用工程师": ["qzxitonggongchengshi", "qzjisuanjiwangluo"], u"技术研发工程师": ["qzjishi", "qzshengchanzhizaozhiwei"], u"办事处首席代表": ["qzxiaoshouzongjian", "qzshichangyingxiao"],
        u"系统架构设计师": ["qzxitongjiagoushi", "qzjisuanjiwangluo"], u"葡萄牙语翻译": ["qzfanyiqita", "qzfanyi"], u"瘦身顾问": ["qzshoushenguwen", "qzyundongjianshenzhiwei"], u"组织发展(OD)": ["qzxingzhengzhuli", "qzxingzhenghouqin"],
        u"人事专员": ["qzrenshizhuli", "qzrenliziyuan"], u"排版设计": ["qzpaiban", "qzbianjichuban"], u"大客户销售管理": ["qzdakehujingli", "qzshichangyingxiao"], u"运维开发": ["qzjishuzhichi", "qzjisuanjiwangluo"],
        u"投资/基金项目经理": ["qztouziguwen", "qzjinrongtouzizhengquan"], u"选址拓展/新店开发": ["qzdianzhang", "qzbaihuolingshou"], u"结构工程师": ["qztjgongchengshi", "qzjianzhuzhuangxiu"], u"场长(农/林/牧/渔业)": ["qznlmyqita", "qznonglin"],
        u"体育运动教练": ["qzyouyongjiaolian", "qzyundongjianshenzhiwei"], u"板房/楦头/底格出格师": ["qzyinhuagong", "qzjigongyibangongren"], u"房地产项目运营": ["qzfdccehua", "qzfangjingjiren"], u"培训督导": ["qzdudao", "qzbaihuolingshou"],
        u"实验室负责人/工程师": ["qzkeyanguanli", "qzjiaoyupeixun"], u"综合业务经理/主管": ["qzyinhangguiyuan", "qzjinrongtouzizhengquan"], u"促销员/导购": ["qzdaogou", "qzbaihuolingshou"], u"核力/火力工程师": ["qzheligongchengshi", "qzdianqinengyuan"],
        u"平面设计总监": ["qzpingmiansheji", "qzmeishusheji"], u"财务经理": ["qzcaiwujingli", "qzcaiwushenji"], u"模具工程师": ["qzmjgongchengshi", "qzjixieyiqiyibiao"], u"人事助理": ["qzrenshizhuli", "qzrenliziyuan"],
        u"商务助理": ["qzshangwujingli", "qzshichangyingxiao"], u"光源与照明工程": ["qzzmgongchengshi", "qzdianqinengyuan"], u"法务助理": ["qzfawurenyuan", "qzfalv"], u"医药技术研发人员": ["qzshengwugongcheng", "qzyiyaoshengwu"],
        u"财务分析员": ["qzcaiwufenxiyuan", "qzcaiwushenji"], u"夹具工程师/技师": ["qzjjgongchengshi", "qzjixieyiqiyibiao"], u"培训经理/主管": ["qzpeixunzhuguan", "qzrenliziyuan"], u"前台接待/总机/接待生": ["qzqiantai", "qzxingzhenghouqin"],
        u"广告项目管理": ["qzguanggaochuangyi", "qzshichanggongguan"], u"工厂经理/厂长": ["qzchangzhang", "qzshengchanzhizaozhiwei"], u"房地产项目/开发/策划经理": ["qzfdccehua", "qzfangjingjiren"], u"营运主管": ["qzdudao", "qzbaihuolingshou"],
        u"电力工程师/技术员": ["qzdligongchengshi", "qzdianqinengyuan"], u"拍卖/担保/典当业务": ["qzxindaiguanli", "qzjinrongtouzizhengquan"], u"中国方言翻译": ["qzfanyiqita", "qzfanyi"], u"国内贸易经理": ["qzgnmyjingli", "qzmaoyiyunshu"],
        u"客户总监": ["qzkehuzongjian", "qzguanggaohuizhanzhiwei"], u"促销主管/督导": ["qzcuxiaojingli", "qzshichanggongguan"], u"列车维修/保养": ["qzjixieweixiugong", "qzjixieyiqiyibiao"], u"合规经理": ["qzfalvguwen", "qzfalv"],
        u"系统管理员/网络管理员": ["qzwangluoguanliyuan", "qzjisuanjiwangluo"], u"进出口/信用证结算": ["qzwaimaozhuanyuan", "qzmaoyiyunshu"], u"日语翻译": ["qzriyufanyi", "qzfanyi"], u"股票/期货操盘手": ["qzcaopanshou", "qzjinrongtouzizhengquan"],
        u"韩语/朝鲜语翻译": ["qzhanyufanyi", "qzfanyi"], u"大客户销售": ["qzdakehujingli", "qzshichangyingxiao"], u"媒介经理": ["qzgongguanjingli", "qzshichanggongguan"], u"汽车装配工艺工程师": ["qzzhuangshimeirong", "qzqiche"],
        u"物流专员/助理": ["qzwuliuzhuanyuan", "qzmaoyiyunshu"], u"西点师/面包糕点加工": ["qzmiandianshi", "qzjiudiancanyin"], u"瑜伽/舞蹈老师": ["qzyouyongjiaolian", "qzyundongjianshenzhiwei"], u"机构客户服务": ["qzxindaiguanli", "qzjinrongtouzizhengquan"],
        u"矿产勘探/地质勘测工程师": ["qzytgongchengshi", "qzjianzhuzhuangxiu"], u"手机软件开发工程师": ["qzruanjiangongchengshi", "qzjisuanjiwangluo"], u"生产文员": ["qzcaigou", "qzbaihuolingshou"], u"广告客户经理": ["qzdakehujingli", "qzshichangyingxiao"],
        u"采购材料、设备质量管理": ["qzzhiliangguanli", "qzshengchanzhizaozhiwei"], u"建筑工程验收": ["qzjzgcyanshou", "qzjianzhuzhuangxiu"], u"总工程师/副总工程师": ["qzzonggongchengshi", "qzshengchanzhizaozhiwei"],
        u"销售行政经理/主管": ["qzxingzhengzhuguan", "qzxingzhenghouqin"], u"销售总监": ["qzxiaoshouzongjian", "qzshichangyingxiao"], u"图书管理员/资料管理员": ["qzjiaoxueguanlirenyuan", "qzjiaoyupeixun"], u"故障分析工程师": ["qzshebeiweixiu", "qzjixieyiqiyibiao"],
        u"废气处理工程师": ["qzwsclgongchengshi", "qzhuanjingbaohu"], u"调研员": ["qzdiaoyanyuan", "qzzixunguwen"], u"广告客户主管/专员": ["qzscyxjingli", "qzshichanggongguan"], u"宾客服务经理": ["qzjdyudingyuan", "qzjiudiancanyin"],
        u"客户经理/主管": ["qzdakehujingli", "qzshichangyingxiao"], u"嵌入式硬件开发(主板机…)": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"], u"搬运工": ["qzbanyungong", "qzjigongyibangongren"], u"保险精算师": ["qzbaoxianjingsuanshi", "qzbaoxianjingjiren"],
        u"列车/地铁司机": ["qzkeyunsiji", "qzsiji"], u"律师/法律顾问": ["qzfalvguwen", "qzfalv"], u"药库主任/药剂师": ["qzyjs", "qzyiyuanyiliao"], u"行李员": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"志愿者/社会工作者": ["qzzhiyuanzhe", "qzjiaoyupeixun"],
        u"IC验证工程师": ["qzdlugongchengshi", "qzdianqinengyuan"], u"市场通路经理/主管": ["qzquyuqudao", "qzshichangyingxiao"], u"媒介专员": ["qzgongguanjingli", "qzshichanggongguan"], u"银行柜员": ["qzyinhangguiyuan", "qzjinrongtouzizhengquan"],
        u"其他语种翻译": ["qzfanyiqita", "qzfanyi"], u"材料工程师": ["qzcailiaoyuan", "qzjianzhuzhuangxiu"], u"质量管理/验货员(QA/QC)": ["qzzhiliangguanli", "qzshengchanzhizaozhiwei"], u"企业策划人员": ["qzqiyecehua", "qzguanggaohuizhanzhiwei"],
        u"物业招商/租赁/租售": ["qzwuyezushou", "qzwuye"], u"光伏系统工程师": ["qzdqgongchengshi", "qzdianqinengyuan"], u"验光师": ["qzygsyanguangshi", "qzyiyuanyiliao"], u"通信电源工程师": ["qzdlugongchengshi", "qzdianqinengyuan"],
        u"物业机电工程师": ["qzjdgongchengshi", "qzjixieyiqiyibiao"], u"公路/桥梁/港口/隧道工程": ["qzhangdaogongcheng", "qzjianzhuzhuangxiu"], u"融资经理/融资主管": ["qzrongzijingli", "qzjinrongtouzizhengquan"],
        u"汽车修理工": ["qzqichexiuligong", "qzjigongyibangongren"], u"渠道/分销专员": ["qzcuxiaojingli", "qzshichanggongguan"], u"服装/纺织设计总监": ["qzgongyisheji", "qzshengchanzhizaozhiwei"], u"硬件工程师": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"],
        u"质量管理/测试工程师(QA/QC工程师)": ["qzzlgongchengshi", "qzjisuanjiwangluo"], u"人事总监": ["qzrenshizongjian", "qzrenliziyuan"], u"电脑放码员": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"动画/3D设计": ["qzdonghuasheji", "qzmeishusheji"],
        u"投资/理财顾问": ["qztouziguwen", "qzjinrongtouzizhengquan"], u"融资专员": ["qzrongzijingli", "qzjinrongtouzizhengquan"], u"切割技工": ["qzqiegejigong", "qzjigongyibangongren"], u"飞机机长/副机长": ["qzluhaikongyun", "qzmaoyiyunshu"],
        u"技术研发经理/主管": ["qzjishuzongjian", "qzjisuanjiwangluo"], u"公关经理": ["qzgongguanjingli", "qzshichanggongguan"], u"电子软件开发(ARM/MCU...)": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"], u"行政总监": ["qzxingzhengzongjian", "qzxingzhenghouqin"],
        u"测试员": ["qzceshigongchengshi", "qzjisuanjiwangluo"], u"保险业务经理/主管": ["qzbxywjingli", "qzbaoxianjingjiren"], u"清洁服务人员": ["qzjudianfuwuyuan", "qzjiudiancanyin"], u"助理业务跟单": ["qzgendanyuan", "qzmaoyiyunshu"],
        u"咨询员": ["qzzixunyuan", "qzzixunguwen"], u"销售代表": ["qzxiaoshoudaibiao", "qzshichangyingxiao"], u"针灸、推拿": ["qzzhenjiutuina", "qzbaojiananmo"], u"安全防护": ["qzjiushengyuan", "qzyundongjianshenzhiwei"],
        u"作家/撰稿人": ["qzbianjijizhe", "qzbianjichuban"], u"商务主管/专员": ["qzshangwujingli", "qzshichangyingxiao"], u"店员/营业员": ["qzyingyeyuan", "qzbaihuolingshou"], u"药品注册": ["qzchanpinyanfa", "qzyiyaoshengwu"],
        u"放射科医师": ["qzwaikeyisheng", "qzyiyuanyiliao"], u"客服经理(非技术)": ["qzkefuzongjian", "qzkefu"], u"公务员": ["qzjiaoshi", "qzjiaoyupeixun"], u"保安人员": ["qzbaoan", "qzjiazhenganbao"], u"保安经理": ["qzbaoan", "qzjiazhenganbao"],
        u"固定收益业务": ["qzzichanguanli", "qzcaiwushenji"], u"房地产项目/开发/策划主管/专员": ["qzfdccehua", "qzfangjingjiren"], u"电子商务总监": ["qzshichangzongjian", "qzshichanggongguan"], u"演员/模特/主持人": ["qzzhuchiren", "qzmeitiyingshi"],
        u"产品/品牌经理": ["qzchanpinjingli", "qzjisuanjiwangluo"], u"生产经理/车间主任": ["qzchejianzhuren", "qzshengchanzhizaozhiwei"], u"经销商": ["qzquyuqudao", "qzshichangyingxiao"], u"麻醉医生": ["qzmazuiyisheng", "qzyiyuanyiliao"],
        u"招聘经理/主管": ["qzzhaopinjingli", "qzrenliziyuan"], u"薪资福利专员/助理": ["qzxzflzhuli", "qzrenliziyuan"], u"经理助理/秘书": ["qzwenmiwenyuan", "qzxingzhenghouqin"], u"VIP专员": ["qzkefuzhuli", "qzkefu"],
        u"FAE 现场应用工程师": ["qzshzcgongchengshi", "qzkefu"], u"广告创意/设计主管/专员": ["qzguanggaochuangyi", "qzshichanggongguan"], u"会计经理/会计主管": ["qzkuaijizhuguan", "qzcaiwushenji"], u"医院管理人员": ["qzyiyuanguanli", "qzyiyuanyiliao"],
        u"临床协调员": ["qzhushichang", "qzyiyuanyiliao"], u"培训/课程顾问": ["qzzhaoshengguwen", "qzjiaoyupeixun"], u"CNC工程师": ["qzcncgongchengshi", "qzjixieyiqiyibiao"], u"客户代表": ["qzxiaoshoudaibiao", "qzshichangyingxiao"],
        u"化工实验室研究员/技术员": ["qzshengwugongcheng", "qzyiyaoshengwu"], u"行政主厨/厨师长": ["qzxicanchushi", "qzjiudiancanyin"], u"医疗器械注册": ["qzylqxtuiguang", "qzyiyaoshengwu"], u"水质检测员": ["qzjianyanjiance", "qzqiche"],
        u"管家部经理/主管": ["qzbkfwjingli", "qzjiudiancanyin"], u"摄影师/摄像师": ["qzshexiang", "qzmeitiyingshi"], u"汽车修理人员": ["qzqichexiuligong", "qzjigongyibangongren"], u"硬件测试": ["qzyingjiangongchengshi", "qzjisuanjiwangluo"],
        u"能源/矿产项目管理": ["qzhuagongjishu", "qzshengchanzhizaozhiwei"], u"畜牧师": ["qzxmsxumushi", "qznonglin"], u"三维/3D设计/制作": ["qzhouqizhizuo", "qzmeitiyingshi"], u"绩效考核经理/主管": ["qzjxkhjingli", "qzrenliziyuan"],
        u"外汇交易": ["qzjijinjinli", "qzjinrongtouzizhengquan"], u"记者": ["qzbianjijizhe", "qzbianjichuban"], u"电信网络工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"], u"移动通信工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"],
        u"保险客户服务/续期管理": ["qzbaoxianguanli", "qzbaoxianjingjiren"], u"供应商/采购质量管理": ["qzzhiliangguanli", "qzshengchanzhizaozhiwei"], u"区域销售经理": ["qzquyuqudao", "qzshichangyingxiao"], u"环保检测": ["qzhuanbaojishu", "qzhuanjingbaohu"],
        u"兼职店员": ["qzyingyeyuan", "qzbaihuolingshou"], u"小学教师": ["qzjiaoshi", "qzjiaoyupeixun"], u"美容顾问/化妆": ["qzhuazhuangzhuli", "qzmeitiyingshi"], u"区域销售总监": ["qzquyuqudao", "qzshichangyingxiao"],
        u"票务/订房服务": ["qzdingpiaofuwu", "qzlvyouzhiwei"], u"房地产投资分析": ["qzfdcpinggu", "qzfangjingjiren"], u"文科教师": ["qzyoujiao", "qzjiaoyupeixun"], u"组长/拉长": ["qzshengchanzhuguan", "qzshengchanzhizaozhiwei"],
        u"开发报建": ["qzfdcxmzhuanyuan", "qzfangjingjiren"], u"网络信息安全工程师": ["qzwlaqgongchengshi", "qzjisuanjiwangluo"], u"促销经理": ["qzcuxiaojingli", "qzshichanggongguan"], u"汽车设计工程师": ["qzjixiegongchengshi", "qzjixieyiqiyibiao"],
        u"船长/副船长": ["qzluhaikongyun", "qzmaoyiyunshu"], u"软件UI设计师/工程师": ["qzwangyesheji", "qzjisuanjiwangluo"], u"国内贸易人员": ["qzgnmyjingli", "qzmaoyiyunshu"], u"叉车工": ["qzchachegong", "qzjigongyibangongren"],
        u"汽车项目管理": ["qzxiangmuguanli", "qzguanggaohuizhanzhiwei"], u"供应链经理": ["qzcaigoujingli", "qzmaoyiyunshu"], u"房产项目配套工程师": ["qzfdcxiangmupeitao", "qzfangjingjiren"], u"银行卡、电子银行业务推广": ["qzyinhangjingli", "qzjinrongtouzizhengquan"],
        u"调墨技师": ["qzpaiban", "qzbianjichuban"], u"乘务员": ["qzczcsiji", "qzsiji"], u"物流经理": ["qzwuliujingli", "qzmaoyiyunshu"], u"中学教师": ["qzjiaoshi", "qzjiaoyupeixun"], u"通信技术工程师": ["qztxjsgongchengshi", "qzjisuanjiwangluo"],
        u"广告创意/设计经理": ["qzguanggaochuangyi", "qzshichanggongguan"], u"电话采编": ["qzbianjijizhe", "qzbianjichuban"], u"医药技术研发管理人员": ["qzkeyanguanli", "qzjiaoyupeixun"], u"培训策划": ["qzpeixuncehua", "qzjiaoyupeixun"],
        u"网站营运专员": ["qzwangzhanyunying", "qzjisuanjiwangluo"], u"工程/设备主管": ["qzsbgongchengshi", "qzjianzhuzhuangxiu"], u"质量管理/测试主管(QA/QC主管)": ["qzzlgongchengshi", "qzjisuanjiwangluo"], u"固废工程师": ["qzwsclgongchengshi", "qzhuanjingbaohu"],
        u"风险控制": ["qzfengxianguanli", "qzjinrongtouzizhengquan"], u"集成电路IC设计/应用工程师": ["qzdlugongchengshi", "qzdianqinengyuan"], u"建筑设备工程师": ["qzgongchengshi", "qzjianzhuzhuangxiu"], u"工艺品/珠宝设计鉴定": ["qzzhubaosheji", "qzmeishusheji"],
        u"商务经理": ["qzshangwujingli", "qzshichangyingxiao"], u"媒介主管": ["qzgongguanjingli", "qzshichanggongguan"], u"个人业务部门经理/主管": ["qzyinhangguiyuan", "qzjinrongtouzizhengquan"],
        u"办事处/分公司/分支机构经理": ["qzxingzhengzhuguan", "qzxingzhenghouqin"], u"仪器/仪表/计量分析师": ["qzjmjxgongchengshi", "qzjixieyiqiyibiao"], u"交互设计师": ["qzwangyesheji", "qzjisuanjiwangluo"], u"旅游产品销售": ["qzjidiao", "qzlvyouzhiwei"],
        u"安装造价工程师": ["qzgongchengjianli", "qzjianzhuzhuangxiu"], u"市场/营销/拓展经理": ["qzscyxjingli", "qzshichanggongguan"], u"环保工程师": ["qzhuanbaojishu", "qzhuanjingbaohu"], u"多媒体设计": ["qzdonghuasheji", "qzmeishusheji"],
        u"人力资源信息系统专员": ["qzrenshiqita", "qzrenliziyuan"], u"产品工艺/制程工程师": ["qzmjgongchengshi", "qzjixieyiqiyibiao"], u"健身顾问/教练": ["qzjianshenjiaolian", "qzyundongjianshenzhiwei"],
        u"互联网软件开发工程师": ["qzruanjiangongchengshi", "qzjisuanjiwangluo"], u"专柜彩妆顾问(BA)": ["qzdianzhang", "qzbaihuolingshou"], u"配音员": ["qzpeiyin", "qzmeitiyingshi"], u"招聘专员/助理": ["qzzhaopinzhuanyuan", "qzrenliziyuan"],
        u"电话销售": ["qzdianhuaxiaoshou", "qzshichangyingxiao"], u"项目主管": ["qzxiangmuzhuguanjingli", "qzyiyaoshengwu"], u"药品生产/质量管理": ["qzypscguanli", "qzyiyaoshengwu"], u"服装/纺织/皮革跟单": ["qzgendanyuan", "qzmaoyiyunshu"],
        u"建筑设计师": ["qzgongchengshi", "qzjianzhuzhuangxiu"], u"产品经理/主管": ["qzchanpinjingli", "qzjisuanjiwangluo"], u"建筑机电工程师": ["qzjdgongchengshi", "qzjixieyiqiyibiao"], u"药品市场推广经理": ["qzyiyaodaibiao", "qzshichangyingxiao"],
        u"活动执行": ["qzqiyecehua", "qzguanggaohuizhanzhiwei"], u"储备经理人": ["qzchubeijingliren", "qzbaoxianjingjiren"], u"版图设计工程师": ["qzdlugongchengshi", "qzdianqinengyuan"], u"医药学检验": ["qzyyxjianyan", "qzyiyuanyiliao"],
        u"激光/光电子技术": ["qzcdgongchengshi", "qzdianqinengyuan"], u"渠道/分销主管": ["qzquyuqudao", "qzshichangyingxiao"], u"合伙人": ["qzrongzijingli", "qzjinrongtouzizhengquan"], u"系统工程师": ["qzxitonggongchengshi", "qzjisuanjiwangluo"],
        u"房地产资产管理": ["qzzichanguanli", "qzcaiwushenji"], u"工业工程师": ["qzjixiegongchengshi", "qzjixieyiqiyibiao"], u"售前/售后技术支持主管": ["qzshzcjingli", "qzkefu"], u"儿科医生": ["qzerkeyisheng", "qzyiyuanyiliao"],
        u"平面设计师": ["qzpingmiansheji", "qzmeishusheji"], u"证券分析师": ["qzfenxishi", "qzjinrongtouzizhengquan"], u"泰语翻译": ["qzfanyiqita", "qzfanyi"], u"飞机维修机械师": ["qzfeixingqisheji", "qzjixieyiqiyibiao"],
        u"房地产项目招投标": ["qzfdcxmzhuanyuan", "qzfangjingjiren"], u"个人业务客户经理": ["qzyinhangguiyuan", "qzjinrongtouzizhengquan"], u"签证专员": ["qzshewaizixunshi", "qzzixunguwen"], u"广告创意总监": ["qzguanggaochuangyi", "qzshichanggongguan"],
        u"驯兽师/助理驯兽师": ["qzxmsxumushi", "qznonglin"], u"清算人员": ["qzyinhangguiyuan", "qzjinrongtouzizhengquan"]}


    return job_dict[job]


if __name__ == '__main__':
    pass